### ISSUE TITLE
AttributeError: module 'textattack' has no attribute 'shared'

### ISSUE THREAD

**Issue by dsvrsec** [QData/TextAttack#110]
I tried to run this line

from textattack.augmentation import EmbeddingAugmenter

and got the error AttributeError: module 'textattack' has no attribute 'shared'

textattack: Downloading https://textattack.s3.amazonaws.com/config.yaml.
100%|██████████| 76.0/76.0 [00:00<00:00, 25.0kB/s]
textattack: Copying /root/.cache/textattack/tmpb4gqlzdx.zip to /root/.cache/textattack/config.yaml.
textattack: Successfully saved config.yaml to cache.
textattack: First time importing textattack: downloading remaining required packages.
textattack: Downloading spaCy required packages.
textattack: Downloading NLTK required packages.
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/lib/python3.6/dist-packages/en_core_web_sm -->
/usr/local/lib/python3.6/dist-packages/spacy/data/en
You can now load the model via spacy.load('en')
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9e97b3efd651> in <module>()
----> 1 from textattack.augmentation import EmbeddingAugmenter

9 frames
/usr/local/lib/python3.6/dist-packages/textattack/constraints/semantics/sentence_encoders/bert/bert.py in <module>()
      2 
      3 from textattack.constraints.semantics.sentence_encoders import SentenceEncoder
----> 4 import textattack.shared.utils as utils
      5 
      6 class BERT(SentenceEncoder):

AttributeError: module 'textattack' has no attribute 'shared'

**Comment by jxmorris12** [comment]
Hi @kumarvrsec -- thanks for filing an issue, and thanks for checking out TextAttack!

I tried reinstalling a fresh copy of textattack and I can't reproduce your issue. That is, after `pip install textattack`, running `from textattack.augmentation import EmbeddingAugmenter` works just fine. Did you install via PyPi (`pip install textattack`) or via source (`git clone && pip install -e .`)?

**Comment by jinyongyoo** [comment]
Could you also let us know what your output is when you run the following code in a Python interpreter?
```
>>> import sys
>>> import textattack
>>> sys.modules['textattack']
```

This should tell you if you're actually importing TextAttack

**Comment by kumarvrsec** [comment]
> Hi @kumarvrsec -- thanks for filing an issue, and thanks for checking out TextAttack!
> 
> I tried reinstalling a fresh copy of textattack and I can't reproduce your issue. That is, after `pip install textattack`, running `from textattack.augmentation import EmbeddingAugmenter` works just fine. 
> 
> Some questions:
> - Did you install via PyPi (`pip install textattack`) or via source (`git clone && pip install -e .`)?
> - What folder are you running this command from?
> - Can you successfully run `import textattack`?

1.i have installed using pip and tried it in google colab

**Comment by jxmorris12** [comment]
Hi @kumarvrsec, we determined that this was due to an issue with an import loop that affected only specific installations of Python. It's now fixed in version `0.0.2.3`. Can you reinstall (`pip install textattack --upgrade`) and let us know if you can now successfully use the `EmbeddingAugmenter`? Thanks.

**Comment by kumarvrsec** [comment]
> Hi @kumarvrsec, we determined that this was due to an issue with an import loop that affected only specific installations of Python. It's now fixed in version `0.0.2.3`. Can you reinstall (`pip install textattack --upgrade`) and let us know if you can now successfully use the `EmbeddingAugmenter`? Thanks.

Thank you,the error is resolved and can you give any end to end example of implementing an attack eg:hotflip

**Comment by jxmorris12** [comment]
That's a great question! We have HotFlip word swap (S5) in the paper already implemented, and it works with our pretrained LSTMs. The easiest way to try it out is like this:

```!python -m textattack --model lstm-mr --recipe hotflip --num-examples 100```

When I ran that just now, the HotFlip attack was only successful 6/91 times (9 mispredictions weren't attacked). This 6% attack success rate makes sense, since HotFlip limits the number of words perturbed at 2. 

You can see our full "recipe" for HotFlip [in this file](https://github.com/QData/TextAttack/blob/master/textattack/attack_recipes/hotflip_ebrahimi_2017.py). Recipe is our word for an implementation of a paper using components from TextAttack.

**Comment by kumarvrsec** [comment]
I have run this code in google colab.But i face this error.Can you please suggest remediation for this.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/textattack/__main__.py", line 20, in <module>
    run_single_threaded(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/shared/scripts/run_attack_single_threaded.py", line 41, in run
    goal_function, attack = parse_goal_function_and_attack_from_args(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/shared/scripts/run_attack_args_helper.py", line 326, in parse_goal_function_and_attack_from_args
    attack = parse_recipe_from_args(model, args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/shared/scripts/run_attack_args_helper.py", line 310, in parse_recipe_from_args
    recipe = eval(f'{RECIPE_NAMES[args.recipe]}(model)')
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/textattack/attack_recipes/hotflip_ebrahimi_2017.py", line 45, in HotFlipEbrahimi2017
    WordEmbeddingDistance(min_cos_sim=0.8)
  File "/usr/local/lib/python3.6/dist-packages/textattack/constraints/semantics/word_embedding_distance.py", line 54, in __init__
    self.word_embeddings = np.load(word_embeddings_file)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/textattack/word_embeddings/paragramcf/paragram.npy'

**Comment by kumarvrsec** [comment]
> That's a great question! We have HotFlip word swap (S5) in the paper already implemented, and it works with our pretrained LSTMs. The easiest way to try it out is like this:
> 
> `!python -m textattack --model lstm-mr --recipe hotflip --num-examples 100`
> 
> When I ran that just now, the HotFlip attack was only successful 6/91 times (9 mispredictions weren't attacked). This 6% attack success rate makes sense, since HotFlip limits the number of words perturbed at 2.
> 
> You can see our full "recipe" for HotFlip [in this file](https://github.com/QData/TextAttack/blob/master/textattack/attack_recipes/hotflip_ebrahimi_2017.py). Recipe is our word for an implementation of a paper using components from TextAttack.

Thank you.Is there any way i can customize it,like changing the pretrained model and data

**Comment by kumarvrsec** [comment]
> That's a great question! We have HotFlip word swap (S5) in the paper already implemented, and it works with our pretrained LSTMs. The easiest way to try it out is like this:
> 
> `!python -m textattack --model lstm-mr --recipe hotflip --num-examples 100`
> 
> When I ran that just now, the HotFlip attack was only successful 6/91 times (9 mispredictions weren't attacked). This 6% attack success rate makes sense, since HotFlip limits the number of words perturbed at 2.
> 
> You can see our full "recipe" for HotFlip [in this file](https://github.com/QData/TextAttack/blob/master/textattack/attack_recipes/hotflip_ebrahimi_2017.py). Recipe is our word for an implementation of a paper using components from TextAttack.

How can i use other word embeddings instead of paragramcf for a specific attack ..eg like hotflip..thanks

**Comment by jxmorris12** [comment]
Hi @kumarvrsec. I'll try to answer your questions one-by-one:

- **The `FileNotFound` error**: I can't get this to reproduce for me, even in a colab notebook. I have a suspicion that you got into some invalid state by canceling an in-progress download or unzip.  Try clearing the cache (`rm -rf ~/.cache/textattack`). If that doesn't work, restart the notebook.
- **Customizing the pre-trained model and data:** when you run attacks from the command-line, you sacrifice some flexibility, since you can only components that we've provided for command-line usage– for example, the pre-trained models. That said provide a bunch of pre-trained models that you can try out (for HotFlip or another attack), and the data sample is automatically chosen for the model. Try replacing `lstm-mr` with one of `{bert,lstm,cnn} x {yelp-sentiment, imdb, mr, ag-news}` (classification) or `{bert-snli, bert-mnli}` (entailment). You can view the full list of options via `python -m textattack --help`. 
- **Other word embeddings:** right now, we only support the counter-fitted glove vectors of dimension 300 from [this paper](https://www.aclweb.org/anthology/N16-1018.pdf). Without too much trouble, you could edit the code to provide your own.

Here are two other suggestions for customization in increasing order of difficulty:

**Suggestion 1: Keep using the command-line, but don't use the attack recipes**
When you specify `--attack-recipe hotflip`, you automatically select the goal function, transformation, constraints, and search method from the [HotFlip paper](https://arxiv.org/pdf/1712.06751.pdf). If you instead specify those components one-by-one, you'll gain a lot more flexibility to tweak things. Here's the command for building HotFlip from components: `python -m textattack --model lstm-mr --num-examples 20 --search-method beam-search:beam_width=10 --transformation word-swap-gradient --constraints repeat stopword max-words-perturbed:max_num_words=2 embedding:min_cos_sim=0.8 part-of-speech --goal-function untargeted-classification`

**Suggestion 2: Use the Python interface**
The way to achieve real flexibility (beyond the components we've implemented and provided in TextAttack) is to run attacks via the Python interface. [Our documentation](https://textattack.readthedocs.io/en/latest/examples/1_Introduction_and_Transformations.html) provides two tutorials that explain this. I can provide more information, too, if you have specific questions.
