### ISSUE TITLE
Transformers Model "textattack/facebook-bart-large-CoLA" is 3 dimensional, but 2 dimensional is expected. 

### ISSUE THREAD

**Issue by 517030910405** [QData/TextAttack#133]
I copied the code from the `examples/text-classification/run_glue.py` from `transformers` and replace the model with your model. 
I found that your model cannot evaluate properly with this structure. 
How should I modify the program to make it run? Thanks
```bash
06/19/2020 19:15:42 - INFO - transformers.configuration_utils -   Model config BartConfig {
  "_num_labels": 3,
  "activation_dropout": 0.0,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartForSequenceClassification"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "d_model": 1024,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 4096,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 12,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 4096,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 12,
  "eos_token_id": 2,
  "finetuning_task": "cola",
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_position_embeddings": 1024,
  "model_type": "bart",
  "normalize_before": false,
  "normalize_embedding": true,
  "num_hidden_layers": 12,
  "output_past": false,
  "pad_token_id": 1,
  "prefix": " ",
  "scale_embedding": false,
  "static_position_embeddings": false,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 142,
      "min_length": 56,
      "no_repeat_ngram_size": 3,
      "num_beams": 4
    }
  },
  "vocab_size": 50265
}

06/19/2020 19:15:43 - INFO - transformers.modeling_utils -   loading weights file https://cdn.huggingface.co/textattack/facebook-bart-large-CoLA/pytorch_model.bin from cache at /lustre/home/acct-cftest/stu374/.cache/torch/transformers/7a795dbf6f525f7fa750bb8016ae30d73b5112d97458b5e4c795c17aa55c9d25.cef22b55ac9bec2f923ff4b9293e3fc819ffe9d74a2c7383e3986152fa09582d
Traceback (most recent call last):
  File "run_glue.py", line 270, in <module>
    main()
  File "run_glue.py", line 156, in main
    tokenizer, model = tokenmodel()
  File "run_glue.py", line 55, in tokenmodel
    model = AutoModelForSequenceClassification.from_pretrained(str)
  File "/lustre/home/acct-cftest/stu374/trans/lib64/python3.6/site-packages/transformers/modeling_auto.py", line 856, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/lustre/home/acct-cftest/stu374/trans/lib64/python3.6/site-packages/transformers/modeling_utils.py", line 753, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for BartForSequenceClassification:
	size mismatch for classification_head.out_proj.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([3, 1024]).
	size mismatch for classification_head.out_proj.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).

```

```python

import dataclasses
import logging
import os
import sys
from dataclasses import dataclass, field
from typing import Callable, Dict, Optional

import numpy as np

from transformers import AutoConfig, AutoModelForSequenceClassification, AutoTokenizer, EvalPrediction, GlueDataset
from transformers import GlueDataTrainingArguments as DataTrainingArguments
from transformers import (
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    glue_compute_metrics,
    glue_output_modes,
    glue_tasks_num_labels,
    set_seed,
)


logger = logging.getLogger(__name__)

def tokenmodel():
    strs = [
        "textattack/distilbert-base-cased-CoLA",#0.46372927911071965 0
        "Huntersx/cola_model",#err 1
        "textattack/bert-base-uncased-CoLA",#0.5338774230813111 2
        "textattack/facebook-bart-large-CoLA",#err 3
        "textattack/roberta-base-CoLA",#0.5365747584120986 4
        "textattack/xlnet-large-cased-CoLA",#0 5
        "textattack/xlnet-base-cased-CoLA",#0.2279360616503532 6
    ]
    str = strs[2]
    tokenizer = AutoTokenizer.from_pretrained(str)
    model = AutoModelForSequenceClassification.from_pretrained(str)
    return tokenizer, model



@dataclass
class ModelArguments:
    """
    Arguments pertaining to which model/config/tokenizer we are going to fine-tune from.
    """

    model_name_or_path: str = field(
        metadata={"help": "Path to pretrained model or model identifier from huggingface.co/models"}
    )
    config_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained config name or path if not the same as model_name"}
    )
    tokenizer_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained tokenizer name or path if not the same as model_name"}
    )
    cache_dir: Optional[str] = field(
        default="cache_dir", metadata={"help": "Where do you want to store the pretrained models downloaded from s3"}
    )
    


def main():
    # See all possible arguments in src/transformers/training_args.py
    # or by passing the --help flag to this script.
    # We now keep distinct sets of args, for a cleaner separation of concerns.

    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))

    if len(sys.argv) == 2 and sys.argv[1].endswith(".json"):
        # If we pass only one argument to the script and it's the path to a json file,
        # let's parse it to get our arguments.
        model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.abspath(sys.argv[1]))
    else:
        model_args, data_args, training_args = parser.parse_args_into_dataclasses()

    if (
        os.path.exists(training_args.output_dir)
        and os.listdir(training_args.output_dir)
        and training_args.do_train
        and not training_args.overwrite_output_dir
    ):
        raise ValueError(
            f"Output directory ({training_args.output_dir}) already exists and is not empty. Use --overwrite_output_dir to overcome."
        )

    # Setup logging
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO if training_args.local_rank in [-1, 0] else logging.WARN,
    )
    logger.warning(
        "Process rank: %s, device: %s, n_gpu: %s, distributed training: %s, 16-bits training: %s",
        training_args.local_rank,
        training_args.device,
        training_args.n_gpu,
        bool(training_args.local_rank != -1),
        training_args.fp16,
    )
    logger.info("Training/evaluation parameters %s", training_args)

    # Set seed
    set_seed(training_args.seed)

    try:
        num_labels = glue_tasks_num_labels[data_args.task_name]
        output_mode = glue_output_modes[data_args.task_name]
    except KeyError:
        raise ValueError("Task not found: %s" % (data_args.task_name))

    # Load pretrained model and tokenizer
    #
    # Distributed training:
    # The .from_pretrained methods guarantee that only one local process can concurrently
    # download model & vocab.

    # config = AutoConfig.from_pretrained(
        # model_args.config_name if model_args.config_name else model_args.model_name_or_path,
        # num_labels=num_labels,
        # finetuning_task=data_args.task_name,
        # cache_dir=model_args.cache_dir,
    # )
    # tokenizer = AutoTokenizer.from_pretrained(
        # model_args.tokenizer_name if model_args.tokenizer_name else model_args.model_name_or_path,
        # cache_dir=model_args.cache_dir,
    # )
    # tokenizer = AutoTokenizer.from_pretrained("textattack/distilbert-base-cased-CoLA")
    # tokenizer = AutoTokenizer.from_pretrained("Huntersx/cola_model")
    # model = AutoModelForSequenceClassification.from_pretrained(
        # model_args.model_name_or_path,
        # from_tf=bool(".ckpt" in model_args.model_name_or_path),
        # config=config,
        # cache_dir=model_args.cache_dir,
    # )
    # model = AutoModelForSequenceClassification.from_pretrained("textattack/distilbert-base-cased-CoLA")
    # model = AutoModelForSequenceClassification.from_pretrained("Huntersx/cola_model")
    tokenizer, model = tokenmodel()
    # model = 
    # Get datasets
    train_dataset = (
        GlueDataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
    )
    print(model_args.cache_dir)
    eval_dataset = (
        GlueDataset(data_args, tokenizer=tokenizer, mode="dev")
        if training_args.do_eval
        else None
    )
    test_dataset = (
        GlueDataset(data_args, tokenizer=tokenizer, mode="test")
        if training_args.do_predict
        else None
    )

    def build_compute_metrics_fn(task_name: str) -> Callable[[EvalPrediction], Dict]:
        def compute_metrics_fn(p: EvalPrediction):
            if output_mode == "classification":
                preds = np.argmax(p.predictions, axis=1)
            elif output_mode == "regression":
                preds = np.squeeze(p.predictions)
            return glue_compute_metrics(task_name, preds, p.label_ids)

        return compute_metrics_fn

    # Initialize our Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=build_compute_metrics_fn(data_args.task_name),
    )

    # Training
    if False:
        trainer.train(
            model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
        )
        trainer.save_model()
        # For convenience, we also re-save the tokenizer to the same directory,
        # so that you can share your model easily on huggingface.co/models =)
        if trainer.is_world_master():
            tokenizer.save_pretrained(training_args.output_dir)

    # Evaluation
    eval_results = {}
    if True:
        logger.info("*** Evaluate ***")

        # Loop to handle MNLI double evaluation (matched, mis-matched)
        eval_datasets = [eval_dataset]
        if data_args.task_name == "mnli":
            mnli_mm_data_args = dataclasses.replace(data_args, task_name="mnli-mm")
            eval_datasets.append(
                GlueDataset(mnli_mm_data_args, tokenizer=tokenizer, mode="dev", cache_dir=model_args.cache_dir)
            )

        for eval_dataset in eval_datasets:
            trainer.compute_metrics = build_compute_metrics_fn(eval_dataset.args.task_name)
            eval_result = trainer.evaluate(eval_dataset=eval_dataset)

            output_eval_file = os.path.join(
                training_args.output_dir, f"eval_results_{eval_dataset.args.task_name}.txt"
            )
            if trainer.is_world_master():
                with open(output_eval_file, "w") as writer:
                    logger.info("***** Eval results {} *****".format(eval_dataset.args.task_name))
                    for key, value in eval_result.items():
                        logger.info("  %s = %s", key, value)
                        writer.write("%s = %s\n" % (key, value))

            eval_results.update(eval_result)

    if True:
        logging.info("*** Test ***")
        test_datasets = [test_dataset]
        if data_args.task_name == "mnli":
            mnli_mm_data_args = dataclasses.replace(data_args, task_name="mnli-mm")
            test_datasets.append(
                GlueDataset(mnli_mm_data_args, tokenizer=tokenizer, mode="test", cache_dir=model_args.cache_dir)
            )

        for test_dataset in test_datasets:
            predictions = trainer.predict(test_dataset=test_dataset).predictions
            if output_mode == "classification":
                predictions = np.argmax(predictions, axis=1)

            output_test_file = os.path.join(
                training_args.output_dir, f"test_results_{test_dataset.args.task_name}.txt"
            )
            if trainer.is_world_master():
                with open(output_test_file, "w") as writer:
                    logger.info("***** Test results {} *****".format(test_dataset.args.task_name))
                    writer.write("index\tprediction\n")
                    for index, item in enumerate(predictions):
                        if output_mode == "regression":
                            writer.write("%d\t%3.3f\n" % (index, item))
                        else:
                            item = test_dataset.get_labels()[item]
                            writer.write("%d\t%s\n" % (index, item))
    return eval_results


def _mp_fn(index):
    # For xla_spawn (TPUs)
    main()



if __name__ == "__main__":
    main()
```

**Comment by jxmorris12** [comment]
Hi @517030910405 --

Ok, short answer, these BART models can't be loaded using the current huggingface setup. There are various problems with the `run_glue` pipeline and I've filed an [issue with `transformers`](https://github.com/huggingface/transformers/issues/4828) that I hope will be resolved soon. Until then, we can't load or use our BART models. 

Here are some other things you should know:
1. Our `textattack/facebook-bart-large-CoLA` model is a fine-tuned version of `facebook/bart-large`. If you want to fine-tune (via the `run_glue` script) you want to use a base model that hasn't been fine-tuned yet. You're trying to fine-tune a model that's already been fine-tuned. 
2. We do have some functional CoLA models that, for whatever reason, work fine given the huggingface setup. Those are the ones we've included in our repository: `"textattack/bert-base-uncased-CoLA",  "textattack/roberta-base-CoLA", "textattack/distilbert-base-cased-CoLA"`. If you're just trying to do some evaluation related to CoLA, load one of those!

```
import transformers
model = transformers. "textattack/roberta-base-CoLA"
```

3. If you're attack the models using _textattack_, it's even easier. Try the RoBERTa cola model:

```bash
pip install textattack
python -m textattack--model roberta-base-cola --num-examples 100 --recipe deepwordbug
```

Hope that's help!

**Comment by 517030910405** [comment]
> Hi @517030910405 --
> 
> Ok, short answer, these BART models can't be loaded using the current huggingface setup. There are various problems with the `run_glue` pipeline and I've filed an [issue with `transformers`](https://github.com/huggingface/transformers/issues/4828) that I hope will be resolved soon. Until then, we can't load or use our BART models.
> 
> Here are some other things you should know:
> 
> 1. Our `textattack/facebook-bart-large-CoLA` model is a fine-tuned version of `facebook/bart-large`. If you want to fine-tune (via the `run_glue` script) you want to use a base model that hasn't been fine-tuned yet. You're trying to fine-tune a model that's already been fine-tuned.
> 2. We do have some functional CoLA models that, for whatever reason, work fine given the huggingface setup. Those are the ones we've included in our repository: `"textattack/bert-base-uncased-CoLA",  "textattack/roberta-base-CoLA", "textattack/distilbert-base-cased-CoLA"`. If you're just trying to do some evaluation related to CoLA, load one of those!
> 
> ```python
> import transformers
> model = transformers.AutoModelForSequenceClassification.from_pretrained("textattack/roberta-base-CoLA")
> ```
> 
> 1. If you're attack the models using _textattack_, it's even easier. Try the RoBERTa cola model:
> 
> ```shell
> pip install textattack
> python -m textattack--model roberta-base-cola --num-examples 100 --recipe deepwordbug
> ```
> 
> Hope that helps!

Thank you very much! 
`textattack` is working well now.
