### ISSUE TITLE
UnboundLocalError: local variable 'output' referenced before assignment

### ISSUE THREAD

**Issue by saum7800** [QData/TextAttack#155]
Hi, 
thank you for the great codebase. It is really helpful.

I attempted to attack a sample dataset of my own on a BERT model. I ran the following line:
`!textattack attack --model-from-huggingface bert-base-uncased --recipe textfooler --dataset-from-file att_dataset.py --num-examples 2`
on Google Colab. this is the error trace I got.

Traceback (most recent call last):
  File "/usr/local/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/textattack_cli.py", line 41, in main
    args.func.run(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/attack/attack_command.py", line 32, in run
    run_single_threaded(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/attack/run_attack_single_threaded.py", line 97, in run
    attack_log_manager.log_result(result)
  File "/usr/local/lib/python3.6/dist-packages/textattack/loggers/attack_log_manager.py", line 35, in log_result
    logger.log_attack_result(result)
  File "/usr/local/lib/python3.6/dist-packages/textattack/loggers/file_logger.py", line 45, in log_attack_result
    self.fout.write(result.__str__(color_method=color_method))
  File "/usr/local/lib/python3.6/dist-packages/textattack/attack_results/attack_result.py", line 61, in __str__
    return "\n\n".join(self.str_lines(color_method=color_method))
  File "/usr/local/lib/python3.6/dist-packages/textattack/attack_results/attack_result.py", line 56, in str_lines
    lines = [self.goal_function_result_str(color_method=color_method)]
  File "/usr/local/lib/python3.6/dist-packages/textattack/attack_results/attack_result.py", line 67, in goal_function_result_str
    orig_colored = self.original_result.get_colored_output(color_method)
  File "/usr/local/lib/python3.6/dist-packages/textattack/goal_function_results/classification_goal_function_result.py", line 50, in get_colored_output
    output, color = self._processed_output
  File "/usr/local/lib/python3.6/dist-packages/textattack/goal_function_results/classification_goal_function_result.py", line 26, in _processed_output
    return output, color
UnboundLocalError: local variable 'output' referenced before assignment

att_dataset.py contains only one line 
`dataset = [("This is the worst feeling ever",1), ("It's not too bad I feel alright I guess",0)]`

Am I doing something wrong? Thanks in advance

**Comment by jxmorris12** [comment]
Hey @saum7800  -- thanks for reporting this issue. There are a few problems here.

1. *A bug in our code*: we messed something up, which we just fixed in 0.1.1! If you `pip install textattack --upgrade` in your notebook, that should fix the `UnboundLocalError`.
2. The model you're loading from huggingface, `bert-base-uncased`, is a model that's **not fine-tuned for classification** -- in short, I don't think this is what you want. If you replace `bert-base-uncased` with a model that's already fine-tuned, like `"textattack/bert-base-uncased-SST-2"`, that should fix that error.
3. The labels in your dataset are flipped, I think -- you probably want to set the ground-truth label for "This is the worst feeling ever" to 0 (negative) and "It's not too bad I feel alright I guess" to 1 (positive).

Just to show how this all fits together, I created a Colab notebook attacking your dataset: https://colab.research.google.com/drive/1BQnuL2GeFDNwJdpoDUHn8E98pmkVL1Df?usp=sharing

Please let me know if this fixes your issue!

**Comment by saum7800** [comment]
Yes this resolves it. Thank you so much for helping out! (that too on such quick notice :) )
