### ISSUE TITLE
eval fails for distilbert-base-uncased-imdb

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#278]
Command:

```
!textattack eval --model distilbert-base-uncased-imdb --num-examples 1000
```

Output:

```
Traceback (most recent call last):
  File "/usr/local/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/textattack_cli.py", line 39, in main
    args.func.run(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/eval_model/eval_model_command.py", line 86, in run
    self.test_model_on_dataset(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/eval_model/eval_model_command.py", line 39, in test_model_on_dataset
    model = parse_model_from_args(args)
  File "/usr/local/lib/python3.6/dist-packages/textattack/commands/attack/attack_args_helpers.py", line 298, in parse_model_from_args
    model, tokenizer, batch_size=args.model_batch_size
AttributeError: 'Namespace' object has no attribute 'model_batch_size'
```

Expected:
to successfully evaluate this model on 1000 samples from IMDB

Reproduced in the [following Colab notebook](https://colab.research.google.com/drive/1WxdCoHchLxA0lz5ZkrP33w0mtCxJ3ZOy?usp=sharing), in the second cell.

**Comment by jxmorris12** [comment]
fixed in v0.2.10! See this [colab reproduction](https://colab.research.google.com/drive/1_n-eMQ4zHrH0sIys8iNMqcIUcm20cBD5?usp=sharing).
