### ISSUE TITLE
Attacking text samples from a specified file

### ISSUE THREAD

**Issue by RishabhMaheshwary** [QData/TextAttack#282]
I executed the following command :
```
textattack attack --model lstm-mr --num-examples 20 --transformation word-swap-embedding  --attack-from-file data/mr --constraints repeat stopword max-words-perturbed^max_num_words=2 embedding^min_cos_sim=0.8 part-of-speech  --goal-function untargeted-classification
```
but got the following error: 

```'NoneType' object has no attribute 'loader'.```

Is there any specified format to attack the text samples from a given file?

**Comment by jxmorris12** [comment]
Hi @RishabhMaheshwary -- sorry for the confusing error message.

`--attack-from-file` is intended to take in a path to a Python file that defines an `Attack` object (with which to run the attack). You provided a path to a text file (I think?) so the loader did something weird and crashed with an error.

I think the flag you're looking for is `--dataset-from-file`, which also takes in a Python file path as argument. If you define a file called `load_mr.py` that loads the dataset like this:

```python
dataset_lines = open('data/mr').readlines()
dataset = [line[1:], int(line[0]) for line in dataset_lines]
# dataset now is now a List<Tuple, String> that looks like  [(0, 'I hated this'), (1, 'I loved this'), ...]```
```

You'll need to customize `load_mr.py` to properly load your data however it's stored. (This assumes that `data/mr` was a text file containing the label and text on each line, one each per line, separated by a space. That's one common way to store files for this dataset, but certainly not the only way.)

After creating this `load_mr.py` file,  try running this command:

```
textattack attack --model lstm-mr --num-examples 20 --transformation word-swap-embedding  --dataset-from-file load_mr.py --constraints repeat stopword max-words-perturbed^max_num_words=2 embedding^min_cos_sim=0.8 part-of-speech  --goal-function untargeted-classification
```

Thanks, and let me know how it goes!

**Comment by RishabhMaheshwary** [comment]
Thanks, will try that. And is there any option to load our own pre-trained model?

**Comment by jxmorris12** [comment]
Yes @RishabhMaheshwary, it's `--model-from-file`!

**Comment by RishabhMaheshwary** [comment]
Used the follwing command:
```
textattack attack --model-from-file model_file.py --num-examples 20 --transformation word-swap-embedding --constraints repeat stopword max-words-perturbed^max_num_words=2 embedding^min_cos_sim=0.8 part-of-speech  --goal-function untargeted-classification --csv-style --log-to-csv outputs
```
Getting the following error:
```
textattack: Loading model and tokenizer from file: model_file.py
textattack: Loading module from `model_file.py`.
Model name './mr' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed './mr/bert_config.json' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "/home/rishabh.maheshwary/anaconda3/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 39, in main
    args.func.run(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/attack_command.py", line 42, in run
    run_single_threaded(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/run_attack_single_threaded.py", line 59, in run
    attack = parse_attack_from_args(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/attack_args_helpers.py", line 191, in parse_attack_from_args
    model = parse_model_from_args(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/attack_args_helpers.py", line 268, in parse_model_from_args
    "Model must be of type "
TypeError: Model must be of type ``textattack.models.ModelWrapper``, got type <class 'NoneType'>
```
```model_file.py```
```
import transformers
import textattack
from textattack.shared import utils
from BERT.tokenization import BertTokenizer
from BERT.modeling import BertForSequenceClassification, BertConfig
pretrained_dir = "./mr"
model = BertForSequenceClassification.from_pretrained(pretrained_dir, num_labels=2)
```
In ```model_file.py``` I loaded my own pretrained model. Is this the right way to do, or am I missing something?

**Comment by jxmorris12** [comment]
Hi @RishabhMaheshwary -- you're really close!

1. It looks like `BertForSequenceClassification` can't load the model from the `./mr` directory. This error is independent of TextAttack. 

2. Please wrap your model in a [model wrapper](https://textattack.readthedocs.io/en/latest/datasets_models/models.html#model-wrappers) to work properly with TextAttack. You can do this by adding the following lines of code to the bottom of your `model_file.py`:

```python
tokenizer = BertTokenizer.from_pretrained(pretrained_dir)
model = textattack.models.wrappers.HuggingFaceModelWrapper(model, tokenizer)
```

**Comment by RishabhMaheshwary** [comment]
Getting the following error now:
```
Traceback (most recent call last):
  File "/home/rishabh.maheshwary/anaconda3/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 39, in main
    args.func.run(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/attack_command.py", line 42, in run
    run_single_threaded(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/run_attack_single_threaded.py", line 106, in run
    for result in attack.attack_dataset(dataset, indices=worklist):
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/shared/attack.py", line 322, in attack_dataset
    for goal_function_result in examples:
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/shared/attack.py", line 308, in _get_examples_from_dataset
    attacked_text, ground_truth_output
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 55, in init_attack_example
    result, _ = self.get_result(attacked_text, check_skip=True)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 66, in get_result
    results, search_over = self.get_results([attacked_text], **kwargs)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 83, in get_results
    model_outputs = self._call_model(attacked_text_list)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 180, in _call_model
    outputs = self._call_model_uncached(uncached_list)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 149, in _call_model_uncached
    outputs = self.model(inputs)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/models/wrappers/huggingface_model_wrapper.py", line 25, in __call__
    ids = self.tokenize(text_input_list)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/models/wrappers/model_wrapper.py", line 24, in tokenize
    return [self.tokenizer.encode(x) for x in inputs]
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/models/wrappers/model_wrapper.py", line 24, in <listcomp>
    return [self.tokenizer.encode(x) for x in inputs]
AttributeError: 'BertTokenizer' object has no attribute 'encode'
```
```dataset.py``` file
```
dataset = []
with open("data/mr", encoding='utf8') as fin:
    for line in fin:
        label, sep, text = line.partition(' ')
        label = int(label)
        dataset.append((text,label))
```
```model_file.py```
```
import torch
import torch.nn as nn
import transformers
import textattack
from textattack.shared import utils
from BERT.tokenization import BertTokenizer
from BERT.modeling import BertForSequenceClassification, BertConfig

class NLI_infer_BERT(nn.Module):
    def __init__(self,
                 pretrained_dir,
                 nclasses,
                 max_seq_length=128,
                 batch_size=32):
        super(NLI_infer_BERT, self).__init__()
        self.model = BertForSequenceClassification.from_pretrained(pretrained_dir, num_labels=nclasses)

        # construct dataset loader
       # self.dataset = NLIDataset_BERT(pretrained_dir, max_seq_length=max_seq_length, batch_size=batch_size)

    def text_pred(self, text_data, batch_size=32):
        # Switch the model to eval mode.
        self.model.eval()

        # transform text data into indices and create batches
        dataloader = self.dataset.transform_text(text_data, batch_size=batch_size)

        probs_all = []
        #         for input_ids, input_mask, segment_ids in tqdm(dataloader, desc="Evaluating"):
        for input_ids, input_mask, segment_ids in dataloader:
            input_ids = input_ids.cuda()
            input_mask = input_mask.cuda()
            segment_ids = segment_ids.cuda()

            with torch.no_grad():
                logits = self.model(input_ids, segment_ids, input_mask)
                probs = nn.functional.softmax(logits, dim=-1)
                probs_all.append(probs)

        return torch.cat(probs_all, dim=0)

pretrained_dir = "mr"
model = NLI_infer_BERT(pretrained_dir, nclasses=2, max_seq_length=256)
tokenizer = BertTokenizer.from_pretrained(pretrained_dir)
model = textattack.models.wrappers.HuggingFaceModelWrapper(model,tokenizer)
```

**Comment by RishabhMaheshwary** [comment]
It seems like there is some issue with the tokenizer part.

**Comment by jxmorris12** [comment]
Well you're importing BertTokenizer from your local `BERT` directory so I can only speculate as to what it's doing. But it looks like your local `BertTokenizer` class doesn't define an `encode()` method, unlike the canonical class `transformers.tokenization_bert.BertTokenizer`.

Maybe try 
```python
from BERT.tokenization import BertTokenizer
```

instead of
```python
from tokenizers import BertTokenizer
```

**Comment by RishabhMaheshwary** [comment]
Used ``` from transformers import tokenizer```
Got the following error:
```
Traceback (most recent call last):
  File "/home/rishabh.maheshwary/anaconda3/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 39, in main
    args.func.run(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/attack_command.py", line 42, in run
    run_single_threaded(args)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/commands/attack/run_attack_single_threaded.py", line 106, in run
    for result in attack.attack_dataset(dataset, indices=worklist):
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/shared/attack.py", line 322, in attack_dataset
    for goal_function_result in examples:
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/shared/attack.py", line 308, in _get_examples_from_dataset
    attacked_text, ground_truth_output
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 55, in init_attack_example
    result, _ = self.get_result(attacked_text, check_skip=True)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 66, in get_result
    results, search_over = self.get_results([attacked_text], **kwargs)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 83, in get_results
    model_outputs = self._call_model(attacked_text_list)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 180, in _call_model
    outputs = self._call_model_uncached(uncached_list)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py", line 149, in _call_model_uncached
    outputs = self.model(inputs)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/models/wrappers/pytorch_model_wrapper.py", line 28, in __call__
    self.model, ids, batch_size=self.batch_size
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/textattack/shared/utils/tensor.py", line 14, in batch_model_predict
    batch_preds = model_predict(batch)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rishabh.maheshwary/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 98, in forward
    raise NotImplementedError
NotImplementedError
```

**Comment by jxmorris12** [comment]
@RishabhMaheshwary `forward()` isn't implemented because `NLI_infer_BERT` has no `forward()` method.

I suppose you could try adding this bit of code to your class:

```python
def forward(self, *args, **kwargs):
  return self.model.forward(*args, **kwargs)
```

**Comment by RishabhMaheshwary** [comment]
Thanks, Its working now.
