### ISSUE TITLE
Test failing due to problem downloading model bert-base-uncased-imdb

### ISSUE THREAD

**Issue by FlorianO** [QData/TextAttack#289]
While running the tests i'll get the following error:
`extattack: Loading pre-trained model from HuggingFace model repository: textattack/bert-base-uncased-imdb
Using /var/folders/fl/xpmc24ds64vfft587kkd_6qh0000gn/T/tfhub_modules to cache modules.
Traceback (most recent call last):
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 39, in main
    args.func.run(args)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/commands/attack/attack_command.py", line 42, in run
    run_single_threaded(args)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/commands/attack/run_attack_single_threaded.py", line 59, in run
    attack = parse_attack_from_args(args)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/commands/attack/attack_args_helpers.py", line 199, in parse_attack_from_args
    recipe = eval(f"{ATTACK_RECIPE_NAMES[args.recipe]}.build(model)")
  File "<string>", line 1, in <module>
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/attack_recipes/textfooler_jin_2019.py", line 66, in build
    use_constraint = UniversalSentenceEncoder(
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/universal_sentence_encoder.py", line 18, in __init__
    self.model = hub.load(tfhub_url)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/tensorflow_hub/module_v2.py", line 114, in load
    obj = tf_v1.saved_model.load_v2(module_path, tags=tags)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 614, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/Users/over/Projects/009_privat/017_TextAttack/MyFork/TextAttack/.venv/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: /var/folders/fl/xpmc24ds64vfft587kkd_6qh0000gn/T/tfhub_modules/063d866c06683311b44b4992fd46003be952409c/{saved_model.pbtxt|saved_model.pb}`

Is there a way to make this more stable?
Can we clean the registry of models when downloads failed/abborted?

**Comment by jxmorris12** [comment]
Hi @FlorianO -- thanks for reporting this issue!! It seems to be some weird error with the tensorflow hub model download, which is trying to load for you the Universal Sentence Encoder.

Can you try re-running the tests with TA_CACHE_DIR set? For example, you could run `TA_CACHE_DIR=/local/tmp pytest tests` if `/local/tmp` is a good place for TextAttack to save models. (keep in mind the cumulative size of that directory could be a few gb since we use a bunch of different models)
