### ISSUE TITLE
Error: dimension out of range - kuleshov attack on wordCNN on external dataset (hatespeech)

### ISSUE THREAD

**Issue by lethaiq** [QData/TextAttack#383]
```
Traceback (most recent call last):
  File "/home/thai.le/anaconda3/envs/py3tf1.6/bin/textattack", line 33, in <module>
    sys.exit(load_entry_point('textattack', 'console_scripts', 'textattack')())
  File "/home/thai.le/Documents/TextAttack/textattack/commands/textattack_cli.py", line 56, in main
    args.func.run(args)
  File "/home/thai.le/Documents/TextAttack/textattack/commands/attack/attack_command.py", line 49, in run
    run_single_threaded(args)
  File "/home/thai.le/Documents/TextAttack/textattack/commands/attack/run_attack_single_threaded.py", line 120, in run
    for result in attack.attack_dataset(dataset, indices=worklist):
  File "/home/thai.le/Documents/TextAttack/textattack/shared/attack.py", line 358, in attack_dataset
    result = self.attack_one(goal_function_result)
  File "/home/thai.le/Documents/TextAttack/textattack/shared/attack.py", line 276, in attack_one
    final_result = self.search_method(initial_result)
  File "/home/thai.le/Documents/TextAttack/textattack/search_methods/search_method.py", line 40, in __call__
    result = self._perform_search(initial_result)
  File "/home/thai.le/Documents/TextAttack/textattack/search_methods/beam_search.py", line 33, in _perform_search
    text, original_text=initial_result.attacked_text
  File "/home/thai.le/Documents/TextAttack/textattack/shared/attack.py", line 188, in get_transformations
    transformed_texts, current_text, original_text
  File "/home/thai.le/Documents/TextAttack/textattack/shared/attack.py", line 257, in filter_transformations
    uncached_texts, current_text, original_text=original_text
  File "/home/thai.le/Documents/TextAttack/textattack/shared/attack.py", line 213, in _filter_transformations_uncached
    filtered_texts = C.call_many(filtered_texts, original_text)
  File "/home/thai.le/Documents/TextAttack/textattack/constraints/constraint.py", line 56, in call_many
    compatible_transformed_texts, reference_text
  File "/home/thai.le/Documents/TextAttack/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 184, in _check_constraint_many
    scores = self._score_list(reference_text, transformed_texts)
  File "/home/thai.le/Documents/TextAttack/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 177, in _score_list
    return self.sim_metric(starting_embeddings, transformed_embeddings)
  File 
```

Dataset:
https://github.com/t-davidson/hate-speech-and-offensive-language

**Comment by lethaiq** [comment]
I am not sure if this relates to #312 though the output error is different.

**Comment by lethaiq** [comment]
This bug is due to `_get_thought_vector` does not return embeddings for words not found in the embeddings.
Suggestion: we can modify the `WordEmbedding`` class in ``word_embedding.py`` to return index of a neural word such as ``the`` if out-of-vocabulary happens.

**Comment by ziqi-zhang** [comment]
@lethaiq Hi, I encountered a similar problem when using kuleshov attack but I don't understand how should I modify WordEmbedding class. Can you please illustrate the workaround more explicitly? Where and how should I modify the code. Thanks!!

**Comment by lethaiq** [comment]
This is a quick fix for me. I replaced this function:
`
    def __getitem__(self, index):
        """Gets the embedding vector for word/id
        Args:
            index (Union[str|int]): `index` can either be word or integer representing the id of the word.
        Returns:
            vector (ndarray): 1-D embedding vector. If corresponding vector cannot be found for `index`, returns `None`.
        """
        if isinstance(index, str):
            try:
                index = self._word2index[index]
            except KeyError:
                index = self._word2index['the']
                # return None
        try:
            return self.embedding_matrix[index]
        except IndexError:
            # word embedding ID out of bounds
            return None
`

in the `class WordEmbedding(AbstractWordEmbedding):` in the `word_embedding.py` file.

**Comment by ziqi-zhang** [comment]
I'll try it!! Thanks!
