### ISSUE TITLE
Error when using recipe `pwws` to attack `bert-base-uncased-sst2` with command `--query-budget 100`

### ISSUE THREAD

**Issue by lijianwen96** [QData/TextAttack#437]
**Describe the bug**
When using recipe `pwws` to attack `bert-base-uncased-sst2` with command `--query-budget 100`, there is an error `IndexError: list index out of range`.

**To Reproduce**
1. Run following command `textattack ...`
`textattack attack --recipe pwws --model bert-base-uncased-sst2 --query-budget 100`

**Screenshots or Traceback**
```
Reusing dataset glue (/root/.cache/huggingface/datasets/glue/sst2/1.0.0/7c99657241149a24692c402a5c3f34d4c9f1df5ac2e4c3759fadea38f6cb29c4)
textattack: Loading datasets dataset glue, subset sst2, split validation.
textattack: Loading pre-trained model from HuggingFace model repository: textattack/bert-base-uncased-SST-2
textattack: Unknown if model of class <class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  weighted-saliency
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapWordNet
  (constraints): 
    (0): RepeatModification
    (1): StopwordModification
  (is_black_box):  True
) 

textattack: Load time: 9.420858383178711s
  0% 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/textattack/commands/textattack_cli.py", line 56, in main
    args.func.run(args)
  File "/usr/local/lib/python3.7/dist-packages/textattack/commands/attack/attack_command.py", line 49, in run
    run_single_threaded(args)
  File "/usr/local/lib/python3.7/dist-packages/textattack/commands/attack/run_attack_single_threaded.py", line 119, in run
    for result in attack.attack_dataset(dataset, indices=worklist):
  File "/usr/local/lib/python3.7/dist-packages/textattack/shared/attack.py", line 347, in attack_dataset
    result = self.attack_one(goal_function_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/shared/attack.py", line 269, in attack_one
    final_result = self.search_method(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/search_method.py", line 40, in __call__
    result = self._perform_search(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/greedy_word_swap_wir.py", line 136, in _perform_search
    if results[0].score > cur_result.score:
IndexError: list index out of range
  0% 0/5 [00:01<?, ?it/s]
```

**System Information (please complete the following information):**
 - OS: ubuntu
 - Library versions: torch==1.8.0+cu101, tensorflow==2.4.1, transformers==4.4.2
 - Textattack version: 0.2.15

**Comment by RishabhMaheshwary** [comment]
The ```search_over``` flag is set to ```True``` when the number of queries exceed the query budget. Before [this](https://github.com/QData/TextAttack/blob/e343f6dbfd931e282412f255ca04b53467c429ac/textattack/search_methods/greedy_word_swap_wir.py#L136) you can add a check. If search_over is ```False``` proceed else return ```initial_result```.

**Comment by lijianwen96** [comment]
> The `search_over` flag is set to `True` when the number of queries exceed the query budget. Before [this](https://github.com/QData/TextAttack/blob/e343f6dbfd931e282412f255ca04b53467c429ac/textattack/search_methods/greedy_word_swap_wir.py#L136) you can add a check. If search_over is `False` proceed else return `initial_result`.

Thank you very much, I will try it later.

**Comment by bksaini078** [comment]
Hello, 

I am also facing the same issue. Any information or workaround to solve the issue. ?

**Comment by d223302** [comment]
When using the latest version, I am having the same issue when the budget is set to 250.

**Comment by bksaini078** [comment]
I was facing the same issue, and then I realized PWWS is not working when we have set max_query size to 100 but text length is also 100. This means, for some text in between PWWS need more than 100 queries to attack, if this is the case, you get this error message. 
I tried with 6000 as max query and it is working fine. You can enter some other values too but make sure the PWWS **Number of queries should not cross the max query size while attacking**

**Comment by VijayKalmath** [comment]
## Issue Analysis 

IndexError when using PWWS with a low query budget. 

```
pip freeze | grep textattack
textattack==0.3.5

$ textattack attack --recipe pwws --model bert-base-uncased-sst2 --query-budget 100

-- Hidden Lines --


[Succeeded / Failed / Skipped / Total] 3 / 0 / 0 / 3:  30%|████████████████████████████████████▎                                                                                    | 3/10 [00:05<00:13,  1.92s/it]Traceback (most recent call last):
  File "/home/vijaykalmath/textattack_env/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/commands/attack_command.py", line 36, in run
    attacker.attack_dataset()
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/attacker.py", line 441, in attack_dataset
    self._attack()
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/attacker.py", line 170, in _attack
    raise e
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/attacker.py", line 168, in _attack
    result = self.attack.attack(example, ground_truth_output)
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/attack.py", line 423, in attack
    result = self._attack(goal_function_result)
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/attack.py", line 371, in _attack
    final_result = self.search_method(initial_result)
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/search_methods/search_method.py", line 36, in __call__
    result = self.perform_search(initial_result)
  File "/home/vijaykalmath/textattack_env/lib/python3.8/site-packages/textattack/search_methods/greedy_word_swap_wir.py", line 142, in perform_search
    if results[0].score > cur_result.score:
IndexError: list index out of range
[Succeeded / Failed / Skipped / Total] 3 / 0 / 0 / 3:  30%|████████████████████████████████████▎                                                                                    | 3/10 [00:09<00:21,  3.12s/it]
```
IndexError is because results is empty list , this is because in the goal_function , the self.num_queries is already matching budget. 

If the self.num_queries is already matching budget,  we should have got search_over == True in the pervious call of get_goal_results. 

The previous call for get_goal_results happends in function _get_index_order and under "weighted-saliency" but we do not update the search_over leading to this scenario in the line below.

https://github.com/QData/TextAttack/blob/e343f6dbfd931e282412f255ca04b53467c429ac/textattack/search_methods/greedy_word_swap_wir.py#L73


### Changes Suggested in textattack/search_methods/greedy_word_swap_wir.py

```				
	        # Update search_over in "weighted-saliency"  condition block.
                swap_results, search_over = self.get_goal_results(transformed_text_candidates)

                # Minor optimization , exit from loop if search_over is set to True.	
                if search_over : 
                    delta_ps += [0.0]*(len_text - len(delta_ps))
                    break
```
Post Change, text attack command line works as expected. 

```
$ textattack attack --recipe pwws --model bert-base-uncased-sst2 --query-budget 100 --disable-stdout --silent
2022-06-03 23:00:31.662536: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Reusing dataset glue (/home/vijaykalmath/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1003.58it/s]
textattack: Loading datasets dataset glue, subset sst2, split validation.
textattack: Loading pre-trained model from HuggingFace model repository: textattack/bert-base-uncased-SST-2
[nltk_data] Downloading package omw-1.4 to /home/vijaykalmath/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
textattack: Unknown if model of class <class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
[Succeeded / Failed / Skipped / Total] 6 / 4 / 0 / 10: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:24<00:00,  2.45s/it]
```
Will open a PR with the fix soon.
