### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Ashiq5** [QData/TextAttack#449]
**Describe the bug**
Returns RecursionError: maximum recursion depth exceeded when trying to train LSTM model adversarially with TextBugger framework on IMDB dataset.

**To Reproduce**
1. Run following command `textattack train --model lstm --dataset imdb --attack textbugger --check-robustness --max-length 2500 --batch-size 64 --epochs 50`
2. See error

**Expected behavior**

**Screenshots or Traceback**
Traceback (most recent call last):
  File "venv/Project5984/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/commands/textattack_cli.py", line 56, in main
    args.func.run(args)
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/commands/train_model/train_model_command.py", line 29, in run
    train_model(args)
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/commands/train_model/run_training.py", line 582, in train_model
    model_wrapper, attack_class, samples_to_attack
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/commands/train_model/run_training.py", line 274, in _generate_adversarial_examples
    attack.attack_dataset(dataset), desc="Attack", total=len(dataset)
  File "venv/Project5984/lib64/python3.6/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attack.py", line 347, in attack_dataset
    result = self.attack_one(goal_function_result)
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attack.py", line 269, in attack_one
    final_result = self.search_method(initial_result)
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/search_methods/search_method.py", line 40, in __call__
    result = self._perform_search(initial_result)
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/search_methods/greedy_word_swap_wir.py", line 128, in _perform_search
    indices_to_modify=[index_order[i]],
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attack.py", line 183, in get_transformations
    current_text, original_text, **kwargs
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attack.py", line 147, in _get_transformations_uncached
    **kwargs,
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/transformations/composite_transformation.py", line 39, in __call__
    new_attacked_texts.update(transformation(*args, **kwargs))
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attacked_text.py", line 92, in __eq__
    if not self.attack_attrs[key] == other.attack_attrs[key]:
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attacked_text.py", line 92, in __eq__
    if not self.attack_attrs[key] == other.attack_attrs[key]:
  File "venv/Project5984/lib64/python3.6/site-packages/textattack/shared/attacked_text.py", line 92, in __eq__
    if not self.attack_attrs[key] == other.attack_attrs[key]:
  [Previous line repeated 241 more times]
RecursionError: maximum recursion depth exceeded

**System Information (please complete the following information):**
 - OS: Linux
 - Library versions (e.g. `torch==1.8.1)
 - Textattack version: latest

**Additional context**

**Comment by qiyanjun** [comment]
@khieu @Ashiq5 we will make a PR to solve this..

**Comment by qiyanjun** [comment]
@sanchit97  @Hanyu-Liu-123 possible to help to solve this?

**Comment by sanchit97** [comment]
@khieu Which versions of `textattack` are you using? I recommend to update to latest version `0.3.3`.
I see @Ashiq5 is using the `0.2.16` version but I could not reproduce the error.
The latest release has much different CLI parameters and it is highly recommended to upgrade to latest version.

**Comment by khieu** [comment]
@sanchit97 i use `0.3.0` and use the code instead of CLI. will try to ugrade to see if it makes a difference. Thanks!
