### ISSUE TITLE
bugs in "textattack train” 

### ISSUE THREAD

**Issue by qiyanjun** [QData/TextAttack#488]
1. .. training issues:
e.g. 
```
textattack train --model-name-or-path albert-base-v2 --dataset snli --per-device-train-batch-size 8 --epochs 5 --learning-rate 1e-5 

:/server/usera/TextAttack ; textattack train --model-name-or-path albert-base-v2 --dataset snli --per-device-train-batch-size 8 --epochs 5 --learning-rate 1e-5 

Iteration:   0%|                                                                         | 0/68769 [00:00<?, ?it/s]/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [2,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [4,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [7,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
....
/miniconda3/envs/textattackenv-master/lib/python3.7/site-packages/textattack/trainer.py", line 505, in training_step
    sample_weights[is_adv_sample] *= self.training_args.alpha
RuntimeError: CUDA error: device-side assert triggered


```

2. model loading issue, e.g., 
``` 
textattack attack --model t5-en-de --recipe seq2sick --num-examples 10


/server/usera/TextAttack ;  textattack attack --model t5-en-de --recipe seq2sick --num-examples 10 
2021-07-22 17:26:22.554522: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Downloading: 5.42kB [00:00, 1.63MB/s]                                                                
Downloading: 3.10kB [00:00, 995kB/s]                                                                 
Downloading and preparing dataset ted_multi_translate/plain_text (download: 335.91 MiB, generated: 754.37 MiB, post-processed: Unknown size, total: 1.06 GiB) to /server/usera/.cache/huggingface/datasets/ted_multi_translate/plain_text/1.0.0/60acc1806272a2861722952467c3b4ac274f1a41d798f7c64b7e36cb590dfc48...
Dataset ted_multi_translate downloaded and prepared to /server/usera/.cache/huggingface/datasets/ted_multi_translate/plain_text/1.0.0/60acc1806272a2861722952467c3b4ac274f1a41d798f7c64b7e36cb590dfc48. Subsequent calls will reuse this data.
Traceback (most recent call last):
  File "/server/usera/miniconda3/envs/textattackenv/bin/textattack", line 33, in <module>
    sys.exit(load_entry_point('textattack', 'console_scripts', 'textattack')())
  File "/net/server/usera/TextAttack/textattack/commands/textattack_cli.py", line 42, in main
    func.run(args)
  File "/net/server/usera/TextAttack/textattack/commands/attack_command.py", line 24, in run
    model_wrapper = ModelArgs._create_model_from_args(attack_args)
  File "/net/server/usera/TextAttack/textattack/model_args.py", line 252, in _create_model_from_args
    model, model.tokenizer
  File "/net/server/usera/TextAttack/textattack/models/wrappers/huggingface_model_wrapper.py", line 20, in __init__
    ), f"`model` must be of type `transformers.PreTrainedModel`, but got type {type(model)}."
AssertionError: `model` must be of type `transformers.PreTrainedModel`, but got type <class 'textattack.models.helpers.t5_for_text_to_text.T5ForTextToText'>.
(textattackenv) 
```

**Comment by qiyanjun** [comment]
More CLI bugs are found: 


~~~~~~~~~~~~~~~~~~~~~

python3 attack/attack_camembert.py 
All model checkpoint layers were used when initializing TFCamembertForSequenceClassification.

All the layers of TFCamembertForSequenceClassification were initialized from the model checkpoint at tblard/tf-allocine.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFCamembertForSequenceClassification for predictions without further training.
Traceback (most recent call last):
  File "attack/attack_camembert.py", line 47, in <module>
    recipe = PWWSRen2019.build(model_wrapper)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/attack_recipes/pwws_ren_2019.py", line 39, in build
    goal_function = UntargetedClassification(model_wrapper)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/goal_functions/classification/untargeted_classification.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/goal_functions/goal_function.py", line 39, in __init__
    self.__class__, model_wrapper.model.__class__
AttributeError: 'HuggingFaceSentimentAnalysisPipelineWrapper' object has no attribute 'model'




~~~~~~~~~~~~~~~~~~~~~

(textattackenv) server1:examples user3$ ./attack/attack_from_components.sh 
Reusing dataset yelp_polarity (/Users/user3/.cache/huggingface/datasets/yelp_polarity/plain_text/1.0.0/a770787b2526bdcbfc29ac2d9beb8e820fbc15a03afd3ebc4fb9d8529de57544)
textattack: Loading datasets dataset yelp_polarity, split test.
textattack: Loading pre-trained model from HuggingFace model repository: textattack/bert-base-uncased-yelp-polarity
textattack: Unknown if model of class <class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
Traceback (most recent call last):
  File "/Users/user3/miniconda3/envs/textattackenv/bin/textattack", line 33, in <module>
    sys.exit(load_entry_point('textattack', 'console_scripts', 'textattack')())
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/commands/textattack_cli.py", line 42, in main
    func.run(args)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/commands/attack_command.py", line 26, in run
    attack_args, model_wrapper
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/attack_args.py", line 678, in _create_attack_from_args
    constraints = cls._create_constraints_from_args(args)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/attack_args.py", line 631, in _create_constraints_from_args
    raise ValueError(f"Error: unsupported constraint {constraint}")
ValueError: Error: unsupported constraint max-words-perturbed:max_percent=0.75



~~~~~~~~~~~~~~~~~~~

(textattackenv) server1:examples user3$ ./augmentation/augment.sh 
usage: [python -m] texattack <command> [<args>] augment [-h] --input-csv
                                                        INPUT_CSV --output-csv
                                                        OUTPUT_CSV
                                                        --input-column
                                                        INPUT_COLUMN
                                                        [--recipe {wordnet,embedding,charswap,eda,checklist,clare}]
                                                        [--pct-words-to-swap PCT_WORDS_TO_SWAP]
                                                        [--transformations-per-example TRANSFORMATIONS_PER_EXAMPLE]
                                                        [--random-seed RANDOM_SEED]
                                                        [--exclude-original]
                                                        [--overwrite]
                                                        [--interactive]
[python -m] texattack <command> [<args>] augment: error: the following arguments are required: --input-csv, --output-csv



~~~~~~~~~~~~~~~~~~~

(textattackenv) server1:examples user3$ ./train/train_lstm_rotten_tomatoes_sentiment_classification.sh 
textattack: Loading textattack model: LSTMForClassification
Traceback (most recent call last):
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/load.py", line 326, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 290, in cached_path
    use_auth_token=download_config.use_auth_token,
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 595, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/1.10.2/datasets/rotten_romatoes/rotten_romatoes.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/load.py", line 338, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 290, in cached_path
    use_auth_token=download_config.use_auth_token,
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 595, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/master/datasets/rotten_romatoes/rotten_romatoes.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user3/miniconda3/envs/textattackenv/bin/textattack", line 33, in <module>
    sys.exit(load_entry_point('textattack', 'console_scripts', 'textattack')())
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/commands/textattack_cli.py", line 42, in main
    func.run(args)
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/commands/train_model_command.py", line 17, in run
    training_args
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/training_args.py", line 500, in _create_dataset_from_args
    train_dataset = HuggingFaceDataset(*dataset_args, split="train")
  File "/Users/user3/user3home/next/workingrepos/TextAttack/textattack/datasets/huggingface_dataset.py", line 103, in __init__
    self._dataset = datasets.load_dataset(self._name, subset)[split]
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/load.py", line 826, in load_dataset
    **config_kwargs,
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/load.py", line 684, in load_dataset_builder
    use_auth_token=use_auth_token,
  File "/Users/user3/miniconda3/envs/textattackenv/lib/python3.7/site-packages/datasets/load.py", line 349, in prepare_module
    combined_path, github_file_path
FileNotFoundError: Couldn't find file locally at rotten_romatoes/rotten_romatoes.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.10.2/datasets/rotten_romatoes/rotten_romatoes.py.
The file is also not present on the master branch on github.

**Comment by qiyanjun** [comment]
# CLI changes on augmentation… recent changes are not compatible with previous CLI augment 




```
(textattackenv) server1:examples user3$ ./augmentation/augment.sh 
usage: [python -m] texattack <command> [<args>] augment [-h] --input-csv
                                                        INPUT_CSV --output-csv
                                                        OUTPUT_CSV
                                                        --input-column
                                                        INPUT_COLUMN
                                                        [--recipe {wordnet,embedding,charswap,eda,checklist,clare}]
                                                        [--pct-words-to-swap PCT_WORDS_TO_SWAP]
                                                        [--transformations-per-example TRANSFORMATIONS_PER_EXAMPLE]
                                                        [--random-seed RANDOM_SEED]
                                                        [--exclude-original]
                                                        [--overwrite]
                                                        [--interactive]
[python -m] texattack <command> [<args>] augment: error: the following arguments are required: --input-csv, --output-csv

```

**Comment by VijayKalmath** [comment]
textattack train --model-name-or-path albert-base-v2 --dataset snli --per-device-train-batch-size 8 --epochs 5 --learning-rate 1e-5  --model-num-labels 3  --filter-train-by-labels 0 1 2

**Comment by jxmorris12** [comment]
Hey @VijayKalmath. 

The changes to T5 look great. 

For the SNLI case, can you we a check to make sure all the labels are accounted for, and throw an `AssertionError` if there are labels unaccounted for? That way we won't get the mysterious "CUDA device-side assert triggered" error.

**Comment by VijayKalmath** [comment]
@jxmorris12  Thank you for confirming the T5 changes. 

Can you please elaborate more on what you mean by ` to make sure all the labels are accounted for`?

**Comment by jxmorris12** [comment]
She ran this command:
```textattack train --model-name-or-path albert-base-v2 --dataset snli --per-device-train-batch-size 8 --epochs 5 --learning-rate 1e-5```
and got this error:
```RuntimeError: CUDA error: device-side assert triggered```

Instead, we should check the number of labels, and if it's not right through `AssertionError: expected 3 labels, got 4` in this case. And also maybe `AssertionError: label -1 not one of [0, 1, 2]`
