### ISSUE TITLE
StopIteration: Caught StopIteration in replica 0 on device 0.

### ISSUE THREAD

**Issue by ardeal** [QData/TextAttack#501]
Hi,
I am running bert + mrpc code, and experiencing the following issue.

Is there any solution for this issue?

```python
Traceback (most recent call last):
  File "main_function_files/task_distill_prune_simultaneously.py", line 1295, in <module>
    main()
  File "main_function_files/task_distill_prune_simultaneously.py", line 1114, in main
    student_logits, student_atts, student_reps = student_model(input_ids, segment_ids, input_mask,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/bert_mrpc/main_function_files/transformer/modeling_pruning.py", line 1132, in forward
    sequence_output, att_output, pooled_output = self.bert(input_ids, token_type_ids, attention_mask,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nlp/bert_mrpc/main_function_files/transformer/modeling_pruning.py", line 829, in forward
    dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration

```

**Comment by jinyongyoo** [comment]
Hi @ardeal. Could you also share the command/code you ran to reproduce this error? From this stack trace alone we cannot tell how TextAttack is involved in this error. Thanks!

**Comment by qiyanjun** [comment]
@ardeal can you reinstall textattack in a single environment... then rerun... seems a library dependent issue..
