### ISSUE TITLE
IndexError in Imdb dataset sample number 3286 

### ISSUE THREAD

**Issue by bangawayoo** [QData/TextAttack#511]
**Describe the bug**
IndexError occurs in `textattack/attack_results/attack_result.py line 104, in diff_color` when attacking a particular sample in the IMDB dataset for some attack recipes. 
Error occurs in sample 3286 for pwws and textfooler, while for the bae recipe the code runs fine. 

**To Reproduce**
1. Run the following command `textattack attack --model bert-base-uncased-imdb --recipe pwws --num-examples-offset 3286`

**Expected behavior**
Attack sample is created and the output is displayed in stdout with the changed tokens in the corresponding color. 

**Screenshots or Traceback**
Error traceback 
```
Traceback (most recent call last):
  File "/home/ky/miniconda3/envs/hg/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 56, in main
    args.func.run(args)
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/commands/attack/attack_command.py", line 49, in run
    run_single_threaded(args)
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/commands/attack/run_attack_single_threaded.py", line 120, in run
    attack_log_manager.log_result(result)
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/loggers/attack_log_manager.py", line 39, in log_result
    logger.log_attack_result(result)
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/loggers/file_logger.py", line 49, in log_attack_result
    self.fout.write(result.__str__(color_method=color_method))
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/attack_results/attack_result.py", line 70, in __str__
    return "\n\n".join(self.str_lines(color_method=color_method))
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/attack_results/attack_result.py", line 66, in str_lines
    lines.extend(self.diff_color(color_method))
  File "/home/ky/miniconda3/envs/hg/lib/python3.7/site-packages/textattack/attack_results/attack_result.py", line 106, in diff_color
    w2 = t2.words[t2_idx]
IndexError: list index out of range
  0%|                                                                                                                                                                                               | 
```
This is the output of  ```t1.words and t2.words ``` before error occurs. The last word of t2 seems to be deleted. 
![Screenshot from 2021-08-09 13-17-26](https://user-images.githubusercontent.com/36688078/128660144-cedaa478-d643-4cd3-9ae5-7c36514236d6.png)

**System Information (please complete the following information):**
 - OS: Linux 
 - `torch==1.7.0, transformers==4.4.2`
 - `textattack==0.2.15`

**Additional context**
Since I only need the original text and the perturbed text (not the changed indices), a workaround was to simply add these lines. 
```
  if t1_idx > len(t1.words)-1:
      t1_idx = len(t1.words)-1
  if t2_idx > len(t2.words)-1:
      t2_idx = len(t2.words)-1 
```
Will this have any effect on the attack algorithm or the logged perturbed text ?

Thanks for the awesome library!

**Comment by bangawayoo** [comment]
Updating to `textattack==0.3.3` fixes this issue. 
I am closing this issue.
