### ISSUE TITLE
Broken dataset-split flag

### ISSUE THREAD

**Issue by huberl** [QData/TextAttack#528]
When using the `dataset-split` CLI argument I get an error. Is there any workaround?

`!textattack attack --recipe pwws --model distilbert-base-uncased-ag-news --dataset-from-huggingface ag_news  --dataset-split train --num-successful-examples 10 
`

```
Traceback (most recent call last):
  File "/home/adversarial2/miniconda3/envs/textattack/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/adversarial2/miniconda3/envs/textattack/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 42, in main
    func.run(args)
  File "/home/adversarial2/miniconda3/envs/textattack/lib/python3.7/site-packages/textattack/commands/attack_command.py", line 15, in run
    dataset = DatasetArgs._create_dataset_from_args(attack_args)
  File "/home/adversarial2/miniconda3/envs/textattack/lib/python3.7/site-packages/textattack/dataset_args.py", line 278, in _create_dataset_from_args
    dataset_args[2] = args.dataset_split
TypeError: 'tuple' object does not support item assignment
```

**System Information:**
 - OS: Linux
 - Textattack version 0.3.3

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 can you take a look at this?

**Comment by Hanyu-Liu-123** [comment]
Hi huberl, thank you for letting us know about this issue!

As the error message indicates, the `_create_dataset_from_args()` function tries to change an element of a tuple. We'll update the method in the next days to fix this. 

In the meantime, what you could do is substituting [this line](https://github.com/QData/TextAttack/blob/7d2de08771d6e1125e391d103ede43bfdaf88a62/textattack/dataset_args.py#L278) with `dataset_args = dataset_args[:1] + (args.dataset_split,) + dataset_args[2:]`

Hope this answers your questions!

**Comment by qiyanjun** [comment]
see PR #533
