### ISSUE TITLE
CLARE implementation not working

### ISSUE THREAD

**Issue by DavidHerel** [QData/TextAttack#589]
**Describe the bug**
I am not able to perform an attack to model with a clare recipe due to the error in the implementation. See attached picture.

**To Reproduce**
1. Run following command `!textattack attack --recipe clare --num-examples 1000 --model bert-base-uncased-mr --dataset-from-huggingface rotten_tomatoes --dataset-split test`
2. See error

**Expected behavior**
Perform an attack on my model using clare recipe.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/49339671/144290029-0264a7da-db0e-4bf6-89a5-3b08be4e74df.png)

**System Information (please complete the following information):**
 - google collab

**Additional context**

**Comment by Hanyu-Liu-123** [comment]
Hi @DavidHerel , thank you so much for letting us know of this.

Is it possible to share a complete traceback that was on Collab so we get a better idea of what it's going on?

**Comment by DavidHerel** [comment]
`Traceback (most recent call last):
  File "/usr/local/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/usr/local/lib/python3.7/dist-packages/textattack/commands/attack_command.py", line 36, in run
    attacker.attack_dataset()
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 441, in attack_dataset
    self._attack()
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 170, in _attack
    raise e
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 168, in _attack
    result = self.attack.attack(example, ground_truth_output)
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 422, in attack
    result = self._attack(goal_function_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 371, in _attack
    final_result = self.search_method(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/search_method.py", line 36, in __call__
    result = self.perform_search(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/beam_search.py", line 33, in perform_search
    text, original_text=initial_result.attacked_text
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 289, in get_transformations
    transformed_texts, current_text, original_text
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 354, in filter_transformations
    uncached_texts, current_text, original_text=original_text
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 313, in _filter_transformations_uncached
    filtered_texts = C.call_many(filtered_texts, original_text)
  File "/usr/local/lib/python3.7/dist-packages/textattack/constraints/constraint.py", line 51, in call_many
    compatible_transformed_texts, reference_text
  File "/usr/local/lib/python3.7/dist-packages/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 179, in _check_constraint_many
    scores = self._score_list(reference_text, transformed_texts)
  File "/usr/local/lib/python3.7/dist-packages/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 136, in _score_list
    iter(transformed_text.attack_attrs["newly_modified_indices"])`

**Comment by Hanyu-Liu-123** [comment]
Hi @DavidHerel, so it turns out that the error is from a discrepancy between clare transformations and the sentence encoder. The full detail can be found in the linked pull request #591 (hopefully we merge it by this weekend).

In the meantime, you could use the [fix-StopIteration-bug branch](https://github.com/QData/TextAttack/tree/fix-StopIteration-bug) to run the clare attacks.

P.S. the clare attack is relatively slow due to the fact it generates a large pool of transformations for the search method to handle, especially if you're planning to run 1000 attacks. I would suggest trying out clare through the API so you can play around with the parameters (such as the number of transformations to generate per attack).
