### ISSUE TITLE
Broken --dataset-split parameter in CLI

### ISSUE THREAD

**Issue by huberl** [QData/TextAttack#599]
**Describe the bug**
The `--dataset-split` parameter in the CLI should allow to select the split of the dataset. However, when running the commands below, an error occurs. This may be caused by the problem that there is no way to define the `subset` via the CLI, but only the split. Both are needed to obtain the dataset, as shown [here](https://github.com/QData/TextAttack/blob/master/textattack/datasets/huggingface_dataset.py#L113). 
If I'm correct, the current implementation simply uses the `--dataset-split` value for the subset.

**To Reproduce**
`textattack attack --recipe pwws --model distilbert-base-uncased-imdb --dataset-from-huggingface imdb  --dataset-split test`
`textattack attack --recipe pwws --model distilbert-base-cased-sst2 --dataset-from-huggingface sst2 --dataset-split test
`

The error can be reproduced by calling the datasets fucntion directly.
```
from datasets import load_dataset
load_dataset('imdb', None)['test']     # Working
load_dataset('imdb', 'test')['test']   # Not-working

```

**Screenshots or Traceback**
###### Working AG_News example
```
textattack attack --recipe pwws --model distilbert-base-uncased-
ag-news --dataset-from-huggingface ag_news --dataset-split test

2021-12-18 11:48:12.555967: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
textattack: Loading datasets dataset ag_news, subset test, split test.
textattack: Loading pre-trained model from HuggingFace model repository: textattack/distilbert-base-uncased-ag-news
```

###### Not working IMDB example
```
textattack attack --recipe pwws --model distilbert-base-uncased-imdb --dataset-from-huggingface imdb  --dataset-split test

2021-12-18 11:50:52.262945: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/commands/attack_command.py", line 22, in run
    dataset = DatasetArgs._create_dataset_from_args(attack_args)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/dataset_args.py", line 281, in _create_dataset_from_args
    dataset = textattack.datasets.HuggingFaceDataset(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/datasets/huggingface_dataset.py", line 113, in __init__
    self._dataset = datasets.load_dataset(self._name, subset)[split]
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/load.py", line 1627, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/load.py", line 1485, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 1020, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 258, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 348, in _create_builder_config
    raise ValueError(f"BuilderConfig {name} not found. Available: {list(self.builder_configs.keys())}")
ValueError: BuilderConfig test not found. Available: ['plain_text']
```

####### Not working SST-2 example
```
textattack attack --recipe pwws --model distilbert-base-cased-sst2 --dataset-from-huggingface sst2 --dataset-split test
2021-12-18 11:53:14.961697: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/commands/attack_command.py", line 22, in run
    dataset = DatasetArgs._create_dataset_from_args(attack_args)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/dataset_args.py", line 281, in _create_dataset_from_args
    dataset = textattack.datasets.HuggingFaceDataset(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/textattack/datasets/huggingface_dataset.py", line 113, in __init__
    self._dataset = datasets.load_dataset(self._name, subset)[split]
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/load.py", line 1627, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/load.py", line 1485, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 1020, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 258, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/adversarial2/miniconda3/envs/textattack_Dec21/lib/python3.8/site-packages/datasets/builder.py", line 348, in _create_builder_config
    raise ValueError(f"BuilderConfig {name} not found. Available: {list(self.builder_configs.keys())}")
ValueError: BuilderConfig test not found. Available: ['cola', 'sst2', 'mrpc', 'qqp', 'stsb', 'mnli', 'mnli_mismatched', 'mnli_matched', 'qnli', 'rte', 'wnli', 'ax']
```

**System Information ():**
 - OS: Linux
 - Library versions:torch==1.10.0, tensorflow==2.5.0, transformers==4.13.0, datasets==1.16.1
 - Textattack version: 0.3.4

**Comment by qiyanjun** [comment]
@huberl good catch!@ mind to submit a PR to fix it? thanks
