### ISSUE TITLE
Index error while running A2T, CNN, MR

### ISSUE THREAD

**Issue by mawady** [QData/TextAttack#601]
**Describe the bug**
Index error while running inference of attack(A2T) over classification(CNN) using dataset (MR)

**To Reproduce**
Colab link: https://colab.research.google.com/drive/10pV0ArRPIG0DjmgPjIXZhldCLRAciYbP?usp=sharing

**Expected behavior**
Running smooth inference over all samples of MR dataset like another combination of A2T and CNN.

**Screenshots or Traceback**
mr__cnn__a2t -- error
textattack: Goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'> compatible with model WordCNNForClassification.
  0%|          | 0/1066 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:1025: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
Traceback (most recent call last):
  File "<ipython-input-10-9789d5ec7ad6>", line 59, in <module>
    run_script(dataset_type, model_type, attack_type)
  File "<ipython-input-8-71af6dc8bf0c>", line 2, in run_script
    results, time_taken  = run_model(dataset_type, model_type, attack_type)
  File "<ipython-input-5-20a74e5deceb>", line 29, in run_model
    results = attacker.attack_dataset()
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 441, in attack_dataset
    self._attack()
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 170, in _attack
    raise e
  File "/usr/local/lib/python3.7/dist-packages/textattack/attacker.py", line 168, in _attack
    result = self.attack.attack(example, ground_truth_output)
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 422, in attack
    result = self._attack(goal_function_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack.py", line 371, in _attack
    final_result = self.search_method(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/search_method.py", line 36, in __call__
    result = self.perform_search(initial_result)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/greedy_word_swap_wir.py", line 122, in perform_search
    index_order, search_over = self._get_index_order(attacked_text)
  File "/usr/local/lib/python3.7/dist-packages/textattack/search_methods/greedy_word_swap_wir.py", line 101, in _get_index_order
    agg_grad = np.mean(gradient[matched_tokens], axis=0)
IndexError: index 1 is out of bounds for axis 0 with size 1
  0%|          | 0/1066 [00:00<?, ?it/s]

**System Information (please complete the following information):**
Colab link is provided!

**Additional context**
N/A

**Comment by VijayKalmath** [comment]
Issue Breakdown 
--
Attack Errors when using the A2T recipe over WordCNN using the dataset (MR) 

Error  : IndexError: index 1 is out of bounds for axis 0 with size 1

Index Error is seen in function `_get_index_order` in `textattack/search_methods/greedy_word_swap_wir.py`. 

```
elif self.wir_method == "gradient":
            victim_model = self.get_victim_model()
            index_scores = np.zeros(initial_text.num_words)
            grad_output = victim_model.get_grad(initial_text.tokenizer_input)
            gradient = grad_output["gradient"]
            word2token_mapping = initial_text.align_with_model_tokens(victim_model)
            for i, word in enumerate(initial_text.words):
                matched_tokens = word2token_mapping[i]

                if not matched_tokens:
                    index_scores[i] = 0.0
                else:
                    agg_grad = np.mean(gradient[matched_tokens], axis=0)   << Imp line
                    index_scores[i] = np.linalg.norm(agg_grad, ord=1)
            search_over = False
```

In the else block above for gradient-based Word Importance Ranking, the `gradient[matched_tokens]` fails when matched_tokens > 0. 

This is because the shape of the gradient is (1, 200) . In Comparison when using A2T with LSTM Model , we see that the gradient shape is (64,200) . This means that the Issue is in the gradient calculation for the model. 

The Gradient Calculation for input embedding layer for a Model is done in function `get_grad` in `textattack/models/wrappers/pytorch_model_wrapper.py`

Currently grad is calculated as 

```
        # grad w.r.t to word embeddings
        grad = torch.transpose(emb_grads[0], 0, 1)[0].cpu().numpy()
```

The Transpose is used because for the LSTM forward , the input to the LSTM Model is the transpose of the `_input` . 

```
    def forward(self, _input):
        # ensure RNN module weights are part of single contiguous chunk of memory
        self.encoder.flatten_parameters()

        emb = self.emb_layer(_input.t())
```

But for the WordCNN Model , the input is `_input` only. 

```
    def forward(self, _input):
        emb = self.emb_layer(_input)
        emb = self.drop(emb)
```

Therefore we need to update the `get_grad` function to fix the Issue , we should not do the transpose for the WordCNN gradients. 

Suggested Code Change : 
----
```
        ### >>>> Changes 
        if  emb_grads[0].shape[1] == 1 : 
            grad = torch.transpose(emb_grads[0], 0, 1)[0].cpu().numpy()
        else : 
            grad = emb_grads[0][0].cpu().numpy()
        ### >>>> Changes 

```


Will open PR with the changed code soon.
