### ISSUE TITLE
Attacking a pre-trained gpt-2 model from Huggingface

### ISSUE THREAD

**Issue by shashank-srikant** [QData/TextAttack#607]
I'm trying to attack a pre-trained `gpt-2` model, and use the example query provided in the project readme to try out an attack. I see the following error. 

Package versions
```
textattack: 0.3.4
transformers: 4.15.0
Python: 3.9
```

Console output
```
$ textattack attack --model-from-huggingface gpt2 -dataset-from-huggingface glue^sst2 --recipe deepwordbug --num-examples 10

22:23:11.481872: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64
22:23:11.481932: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

22:23:11.481872: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64

22:23:11.481932: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Reusing dataset glue (/home/.cache/huggingface/datasets/glue/sst2/1.0.0/7c99657241149a24692c402a5c3f34d4c9f1df5ac2e4c3759fadea38f6cb29c4)
Reusing dataset glue (/home/.cache/huggingface/datasets/glue/sst2/1.0.0/7c99657241149a24692c402a5c3f34d4c9f1df5ac2e4c3759fadea38f6cb29c4)

: Loading [94mdatasets[0m dataset [94mglue[0m, subset [94msst2[0m, split [94mtrain[0m.
: Loading [94mdatasets[0m dataset [94mglue[0m, subset [94msst2[0m, split [94mtrain[0m.
: Loading pre-trained model from HuggingFace model repository: [94mgpt2[0m
: Loading pre-trained model from HuggingFace model repository: [94mgpt2[0m
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
: Unknown if model of class <class 'transformers.models.gpt2.modeling_gpt2.GPT2ForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
: Unknown if model of class <class 'transformers.models.gpt2.modeling_gpt2.GPT2ForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.
  0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0/10 [00:00<?, ?it/s]Using pad_token, but it is not set yet.

Using pad_token, but it is not set yet.

Traceback (most recent call last):
  File "/home/bin/textattack", line 8, in <module>
Traceback (most recent call last):
  File "/home/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/lib/python3.9/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    sys.exit(main())
  File "/home/lib/python3.9/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/lib/python3.9/site-packages/textattack/commands/attack_command.py", line 36, in run
    func.run(args)
  File "/home/lib/python3.9/site-packages/textattack/commands/attack_command.py", line 36, in run
    attacker.attack_dataset()
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 441, in attack_dataset
    attacker.attack_dataset()
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 441, in attack_dataset
    self._attack()
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 170, in _attack
    self._attack()
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 170, in _attack
    raise e
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 168, in _attack
    raise e
  File "/home/lib/python3.9/site-packages/textattack/attacker.py", line 168, in _attack
    result = self.attack.attack(example, ground_truth_output)
  File "/home/lib/python3.9/site-packages/textattack/attack.py", line 416, in attack
    result = self.attack.attack(example, ground_truth_output)
  File "/home/lib/python3.9/site-packages/textattack/attack.py", line 416, in attack
    goal_function_result, _ = self.goal_function.init_attack_example(
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 68, in init_attack_example
    goal_function_result, _ = self.goal_function.init_attack_example(
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 68, in init_attack_example
    result, _ = self.get_result(attacked_text, check_skip=True)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 79, in get_result
    result, _ = self.get_result(attacked_text, check_skip=True)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 79, in get_result
    results, search_over = self.get_results([attacked_text], **kwargs)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 96, in get_results
    results, search_over = self.get_results([attacked_text], **kwargs)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 96, in get_results
    model_outputs = self._call_model(attacked_text_list)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 216, in _call_model
    model_outputs = self._call_model(attacked_text_list)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 216, in _call_model
    outputs = self._call_model_uncached(uncached_list)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 165, in _call_model_uncached
    outputs = self._call_model_uncached(uncached_list)
  File "/home/lib/python3.9/site-packages/textattack/goal_functions/goal_function.py", line 165, in _call_model_uncached
    batch_preds = self.model(batch)
  File "/home/lib/python3.9/site-packages/textattack/models/wrappers/huggingface_model_wrapper.py", line 43, in __call__
    batch_preds = self.model(batch)
  File "/home/lib/python3.9/site-packages/textattack/models/wrappers/huggingface_model_wrapper.py", line 43, in __call__
    inputs_dict = self.tokenizer(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2418, in __call__
    inputs_dict = self.tokenizer(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2418, in __call__
    return self.batch_encode_plus(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2600, in batch_encode_plus
    return self.batch_encode_plus(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2600, in batch_encode_plus
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2313, in _get_padding_truncation_strategies
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
  File "/home/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2313, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```
 --- 
It complains of not finding the right tokenizer. 
To circumvent this, I attempted to use custom code to pass my model. 
In this case however, I see that the embedding layer (expectedly) throws an error because the inputs are `torch.long`s (which the embedding layer expects), but gradients can only be stored in `torch.float`s. 

I believe `HuggingFaceModelWrapper` is designed to take care of just such issues. So i may be missing something in setting it up right.
Can someone point me to the right resources please to get this attack right.

Thanks!

Custom code 
```
from textattack.models.wrappers import HuggingFaceModelWrapper
from textattack.attack_recipes import HotFlipEbrahimi2017
from textattack import Attacker

model_wrapper = HuggingFaceModelWrapper(model_encoder, tokenizer)
attack = HotFlipEbrahimi2017.build(model_wrapper)
attacker = Attacker(attack, valid_dataset)
attacker.attack_dataset()
```

Corresponding output
```
Traceback (most recent call last):
  File "/home/attack.py", line 241, in <module>
Traceback (most recent call last):
  File "/home/attack.py", line 241, in <module>
    train_labels, train_predict, train_loss = train(model_fc, train_dataloader, loss_function, optimizer, scheduler, device)
  File "/home/attack.py", line 128, in train
    train_labels, train_predict, train_loss = train(model_fc, train_dataloader, loss_function, optimizer, scheduler, device)
  File "/home/attack.py", line 128, in train
    for batch in tqdm(dataloader, total=len(dataloader)):
  File "/home/lib/python3.9/site-packages/tqdm/std.py", line 1133, in __iter__
    for batch in tqdm(dataloader, total=len(dataloader)):
  File "/home/lib/python3.9/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/home/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    for obj in iterable:
  File "/home/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._next_data()
  File "/home/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/attack.py", line 108, in __call__
    return self.collate_fn(data)
  File "/home/attack.py", line 108, in __call__
    v.requires_grad = True
RuntimeError: only Tensors of floating point and complex dtype can require gradients
    v.requires_grad = True
RuntimeError: only Tensors of floating point and complex dtype can require gradients
```

**Comment by qiyanjun** [comment]
@srujanjoshi mind to help?

**Comment by VijayKalmath** [comment]
@shashank-srikant 

Thank you for opening the issue. 

The error seems to be because gpt2 and distilgpt2 do not have pad_tokens in their model and tokenizer definition. 

This is because pad_tokens were not used in the Pre-training of gpt2 as mentioned in https://github.com/huggingface/transformers/issues/2630.

In order to overcome this, I propose we add the following code block before we call the tokenizer in 
https://github.com/QData/TextAttack/blob/dce49a0e3502dfedf4b06227a3aa323c386c9b24/textattack/models/wrappers/huggingface_model_wrapper.py#L43

```
if not self.tokenizer._pad_token : 
    # Set pad_token to current eos_token 
    self.tokenizer.pad_token = self.tokenizer.eos_token
    
    # Set pad_token_id for model the tokenizer is associated to 
    self.model.config.pad_token_id = self.tokenizer.pad_token_id
```
@jxmorris12  Can you if this change looks good. 

I am assuming that every model has eos_token. If we cannot work under this assumption,  we will have to add a check to see if eos_token is present and if it's not present we will have to set pad_token to a unique token like [[PAD]] or '<|endoftext|>'. 

@shashank-srikant for the second issue, can you share the code for creating the model_encoder and tokenizer that you use.  


Thanks!

**Comment by jxmorris12** [comment]
@shashank-srikant I don't think this question makes sense. GPT-2 is a pre-trained decoder-only model. It's not task-specific, and even if it was, it doesn't have a classification head on it. You can't run the deepwordbug algorithm with a model that *decodes* (generates) text (like GPT-n) you need a model that *encodes* text.

**Comment by jxmorris12** [comment]
@VijayKalmath your fix will fix the error thrown in the issue but it'll just raise another error somewhere else bc GPT generates text so the DeepWordBug goal function won't work

**Comment by VijayKalmath** [comment]
Hello @jxmorris12, 

I too thought of how gpt2 works here, but for gpt2 with classification heads, I thought the fix would still be needed. 

Does it still make sense to add the fix for such models?

**Comment by jxmorris12** [comment]
GPT-2 outputs text, I don't think you can just attach a classification head to it! But in the event that we did (via few-shot classification or something like that) we'd need an entire new model wrapper

**Comment by RealPolitiX** [comment]
One can scalarize the generated output to approximate a classification head, given a fixed decoding method. This could work in simple settings such as multiple-choice question answering or sentiment classification, especially with an instruction-tuned model that's becoming more common these days.
