### ISSUE TITLE
KeyError: -1 while evaluating bert-base-uncased on SNLI against Bert-Attack

### ISSUE THREAD

**Issue by dangne** [QData/TextAttack#634]
**Describe the bug**
I simply ran the command `textattack attack --model bert-base-uncased-snli --recipe bert-attack --num-examples 1000`

**To Reproduce**
1. Run following command `textattack attack --model bert-base-uncased-snli --recipe bert-attack --num-examples 1000`
2. See error at example 46

**Expected behavior**
It should run without error

**Screenshots or Traceback**
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/textattack/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 42, in main
    func.run(args)
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/commands/attack_command.py", line 29, in run
    attacker.attack_dataset()
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/attacker.py", line 429, in attack_dataset
    self._attack()
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/attacker.py", line 156, in _attack
    example, ground_truth_output = self.dataset[idx]
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/datasets/huggingface_dataset.py", line 170, in __getitem__
    return self._format_as_dict(self._dataset[i])
  File "/root/miniconda3/envs/textattack/lib/python3.8/site-packages/textattack/datasets/huggingface_dataset.py", line 147, in _format_as_dict
    output = self.label_map[output]
KeyError: -1
[Succeeded / Failed / Skipped / Total] 40 / 0 / 6 / 46:   5%|████████▏                | 46/1000 [00:17<06:08,  2.59it/s]

```

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS 
 - Library versions: `torch==1.8.1, transformers==4.11.2`
 - Textattack version: 0.3.0

**Comment by dangne** [comment]
Okay so we have to add the `--filter-by-labels 0 1 2` argument since the SNLI dataset may contain instances that have -1 label (as noted by [huggingface](https://huggingface.co/datasets/snli)).
