### ISSUE TITLE
Universal -sentence-encoder could not be downloaded

### ISSUE THREAD

**Issue by buthi** [QData/TextAttack#651]
when using textattack I meet this problem:
/tmp/tfhub_modules to cache modules.
Downloading TF-Hub Module 'https://tfhub.dev/google/universal-sentence-encoder/3'.
Traceback (most recent call last):
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] 连接超时

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysc/anaconda3/envs/textattack/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/commands/attack_command.py", line 36, in run
    attacker.attack_dataset()
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attacker.py", line 441, in attack_dataset
    self._attack()
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attacker.py", line 170, in _attack
    raise e
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attacker.py", line 168, in _attack
    result = self.attack.attack(example, ground_truth_output)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attack.py", line 423, in attack
    result = self._attack(goal_function_result)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attack.py", line 371, in _attack
    final_result = self.search_method(initial_result)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/search_methods/search_method.py", line 36, in __call__
    result = self.perform_search(initial_result)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/search_methods/greedy_word_swap_wir.py", line 134, in perform_search
    indices_to_modify=[index_order[i]],
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attack.py", line 289, in get_transformations
    transformed_texts, current_text, original_text
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attack.py", line 354, in filter_transformations
    uncached_texts, current_text, original_text=original_text
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/attack.py", line 315, in _filter_transformations_uncached
    filtered_texts = C.call_many(filtered_texts, current_text)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/constraints/constraint.py", line 51, in call_many
    compatible_transformed_texts, reference_text
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 179, in _check_constraint_many
    scores = self._score_list(reference_text, transformed_texts)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/constraints/semantics/sentence_encoders/sentence_encoder.py", line 152, in _score_list
    embeddings = self.encode(starting_text_windows + transformed_text_windows)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/universal_sentence_encoder.py", line 30, in encode
    self.model = hub.load(self._tfhub_url)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/module_v2.py", line 92, in load
    module_path = resolve(handle)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/module_v2.py", line 47, in resolve
    return registry.resolver(handle)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/compressed_module_resolver.py", line 68, in __call__
    self._lock_file_timeout_sec())
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/resolver.py", line 418, in atomic_download
    download_fn(handle, tmp_dir)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/compressed_module_resolver.py", line 63, in download
    response = self._call_urlopen(request)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/site-packages/tensorflow_hub/resolver.py", line 522, in _call_urlopen
    return urllib.request.urlopen(request)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/ysc/anaconda3/envs/textattack/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] 连接超时>
  0%|                                                   | 0/100 [02:11<?, ?it/s]

I tried to change the url in /home/ysc/TextAttack/textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/universal_sentence_encoder.py :
        if large:
            tfhub_url = "https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5"
        else:
            tfhub_url = "https://hub.tensorflow.google.cn/google/collections/universal-sentence-encoder/1"
but nothing changed

**Comment by buthi** [comment]
Thank you I have solved the problem

**Comment by jxmorris12** [comment]
I fixed this in #644

**Comment by zhuhai-ustc** [comment]
> Thank you I have solved the problem

hello @buthi ,
I have encountered the same problem, how can I solve it? thanks!

**Comment by jxmorris12** [comment]
@zhuhai-ustc are you using the latest version of TextAttack?

**Comment by buthi** [comment]
> > Thank you I have solved the problem
> 
> hello @buthi , I have encountered the same problem, how can I solve it? thanks!

把环境里面那个tensorflow的url改成国内镜像的就行了

**Comment by zhy605420954** [comment]
> > > Thank you I have solved the problem
> > 
> > 
> > hello @buthi , I have encountered the same problem, how can I solve it? thanks!
> 
> 把环境里面那个tensorflow的url改成国内镜像的就行了

可以解释的详细一点吗。

**Comment by code-chendl** [comment]
> 把环境里面那个tensorflow的url改成国内镜像的就行了

\textattack\constraints\semantics\sentence_encoders\universal_sentence_encoder\universal_sentence_encoder.py
文件中line19之后对应位置改成——
```python
if large:
        #源代码：tfhub_url = "https://tfhub.dev/google/universal-sentence-encoder-large/5"
        tfhub_url = "https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5" #国内镜像
else:
        #源代码：tfhub_url = "https://tfhub.dev/google/universal-sentence-encoder/3"
        tfhub_url = "https://hub.tensorflow.google.cn/google/universal-sentence-encoder/4" #国内镜像
```
