### ISSUE TITLE
Issues using TextAttack on colab

### ISSUE THREAD

**Issue by JohnGiorgi** [QData/TextAttack#670]
**Describe the bug**

I am having issues installing/using `textattack` on colab. I am following the installation instructions in the [TextAttack-End-to-End notebook](https://textattack.readthedocs.io/en/latest/2notebook/0_End_to_End.html?highlight=colab#TextAttack-End-to-End) from the documentation.

**To Reproduce**

1. Start a fresh colab notebook
2. run `!pip3 install textattack[tensorflow]`
3. run `!textattack --help`
4. The following error is reported:

```
2022-06-17 23:40:33.352746: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/local/bin/textattack", line 5, in <module>
    from textattack.commands.textattack_cli import main
  File "/usr/local/lib/python3.7/dist-packages/textattack/__init__.py", line 11, in <module>
    from .attack_args import AttackArgs, CommandLineAttackArgs
  File "/usr/local/lib/python3.7/dist-packages/textattack/attack_args.py", line 13, in <module>
    from textattack.shared.utils import ARGS_SPLIT_TOKEN, load_module_from_file
  File "/usr/local/lib/python3.7/dist-packages/textattack/shared/__init__.py", line 11, in <module>
    from . import utils
  File "/usr/local/lib/python3.7/dist-packages/textattack/shared/utils/__init__.py", line 3, in <module>
    from .strings import *
  File "/usr/local/lib/python3.7/dist-packages/textattack/shared/utils/strings.py", line 4, in <module>
    import flair
  File "/usr/local/lib/python3.7/dist-packages/flair/__init__.py", line 23, in <module>
    from . import (  # noqa: E402 import after setting device
  File "/usr/local/lib/python3.7/dist-packages/flair/models/__init__.py", line 1, in <module>
    from .clustering import ClusteringModel
  File "/usr/local/lib/python3.7/dist-packages/flair/models/clustering.py", line 14, in <module>
    from flair.embeddings import DocumentEmbeddings
  File "/usr/local/lib/python3.7/dist-packages/flair/embeddings/__init__.py", line 5, in <module>
    from .document import (
  File "/usr/local/lib/python3.7/dist-packages/flair/embeddings/document.py", line 12, in <module>
    from flair.embeddings.token import FlairEmbeddings, StackedEmbeddings, TokenEmbeddings
  File "/usr/local/lib/python3.7/dist-packages/flair/embeddings/token.py", line 9, in <module>
    import gensim
  File "/usr/local/lib/python3.7/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.7/dist-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/usr/local/lib/python3.7/dist-packages/gensim/corpora/indexedcorpus.py", line 15, in <module>
    from gensim import interfaces, utils
  File "/usr/local/lib/python3.7/dist-packages/gensim/interfaces.py", line 21, in <module>
    from gensim import utils, matutils
  File "/usr/local/lib/python3.7/dist-packages/gensim/matutils.py", line 1076, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "__init__.pxd", line 199, in init gensim._matutils
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
```

**Expected behavior**

I expect to be able to install `textattack` in colab and call `textattack --help` without error.

**Screenshots or Traceback**

You can reproduce this error using the [TextAttack-End-to-End notebook](https://textattack.readthedocs.io/en/latest/2notebook/0_End_to_End.html?highlight=colab#TextAttack-End-to-End) from the documentation and calling `textattack --help` after `pip` installing `textattack`.

**System Information (please complete the following information):**

Running in a colab notebook using the latest version of `textattack` (textattack==0.3.5)

**Additional context**

This appears to be an issue with the version of `gensim` currently installed by `textattack`. Upgrading to the latest version fixes the problem (`!pip install --upgrade gensim`). I'd be happy to bump the `gensim` version in PR if that's an acceptable fix!

**Comment by VijayKalmath** [comment]
```
Requirement already satisfied: gensim>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from flair->textattack[tensorflow]) (3.6.0)
```

gensim requirement is dictated by flair package and not by textattack. So bumping that up might not be the right fix. 

I found that upgrading the numpy version to 1.21.0 or higher also solves the issue. @JohnGiorgi Can you check the same solution and then open a PR with the new numpy version after checking none of the current tests fail

**Comment by JohnGiorgi** [comment]
Thanks @VijayKalmath, you are right. Bumping to `numpy>=1.21.0` fixed the problem for me. Will open a PR!
