### ISSUE TITLE
Bug for T5 summarization using seq2sick

### ISSUE THREAD

**Issue by tangxiangru** [QData/TextAttack#683]
!textattack attack --model t5-en-de --recipe seq2sick --num-examples 100

2022-08-02 21:47:58.137829: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Downloading: 5.42kB [00:00, 1.97MB/s]                                           
Downloading: 3.10kB [00:00, 1.12MB/s]                                           
Downloading and preparing dataset ted_multi_translate/plain_text (download: 335.91 MiB, generated: 754.37 MiB, post-processed: Unknown size, total: 1.06 GiB) to /home/xt86/.cache/huggingface/datasets/ted_multi_translate/plain_text/1.0.0/60acc1806272a2861722952467c3b4ac274f1a41d798f7c64b7e36cb590dfc48...
Downloading: 100%|███████████████████████████| 352M/352M [00:12<00:00, 29.1MB/s]
Dataset ted_multi_translate downloaded and prepared to /home/xt86/.cache/huggingface/datasets/ted_multi_translate/plain_text/1.0.0/60acc1806272a2861722952467c3b4ac274f1a41d798f7c64b7e36cb590dfc48. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████| 3/3 [00:02<00:00,  1.25it/s]
textattack: Goal function <class 'textattack.goal_functions.text.non_overlapping_output.NonOverlappingOutput'> compatible with model T5ForTextToText.
Traceback (most recent call last):
  File "/gpfs/ysm/project/gerstein/xt86/conda_envs/legacy_application/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/gpfs/ysm/project/gerstein/xt86/conda_envs/legacy_application/lib/python3.7/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/gpfs/ysm/project/gerstein/xt86/conda_envs/legacy_application/lib/python3.7/site-packages/textattack/commands/attack_command.py", line 36, in run
    attacker.attack_dataset()
  File "/gpfs/ysm/project/gerstein/xt86/conda_envs/legacy_application/lib/python3.7/site-packages/textattack/attacker.py", line 423, in attack_dataset
    if self.dataset.shuffled and self.attack_args.checkpoint_interval:
AttributeError: 'TedMultiTranslationDataset' object has no attribute 'shuffled'

**Comment by jxmorris12** [comment]
Please reclone and try again. I think this works now.
