### ISSUE TITLE
`pip install textattack` with error message `ERROR: Cannot uninstall 'certifi'.`

### ISSUE THREAD

**Issue by otterlover24** [QData/TextAttack#692]
**Describe the bug**
`pip install textattack` with error message `ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**To Reproduce**
- Running on AWS Sagemaker
- Set up conda environement via `(studiolab) studio-lab-user@default:~$ conda create --name OL_textattack python=3.6`
- Then ran `pip install textattack`

**Expected behavior**
textattack was supposed to be installed afer running `pip install textattack`

**Screenshots or Traceback**
  Attempting uninstall: certifi
    Found existing installation: certifi 2016.9.26
ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
(OL_textattack) studio-lab-user@default:~$ textattack --help
bash: textattack: command not found

**System Information (please complete the following information):**
- Running on AWS Sagemaker
- Set up conda environement via `(studiolab) studio-lab-user@default:~$ conda create --name OL_textattack python=3.6`
- Then ran `pip install textattack`

**Additional context**

**Comment by otterlover24** [comment]
Full Bash session on AWS Sagemaker Studio Lab CPU instance console for context:

```
(studiolab) studio-lab-user@default:~$ conda env list
# conda environments:
#
OL_demo_term             /home/studio-lab-user/.conda/envs/OL_demo_term
default                  /home/studio-lab-user/.conda/envs/default
studiolab             *  /home/studio-lab-user/.conda/envs/studiolab
base                     /opt/conda

(studiolab) studio-lab-user@default:~$ conda create --name OL_textattack python=3.6
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/studio-lab-user/.conda/envs/OL_textattack

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2022.6.15-ha878542_0
  certifi            conda-forge/linux-64::certifi-2016.9.26-py36_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libsqlite          conda-forge/linux-64::libsqlite-3.39.3-h753d276_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_2
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1
  openssl            conda-forge/linux-64::openssl-1.1.1q-h166bdaf_0
  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.6.15-hb7a2778_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.6-2_cp36m
  readline           conda-forge/linux-64::readline-8.1.2-h0f457ee_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py36h5fab9bb_3
  sqlite             conda-forge/linux-64::sqlite-3.39.3-h4ff8645_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate OL_textattack
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(studiolab) studio-lab-user@default:~$ conda activate OL_textattack
(OL_textattack) studio-lab-user@default:~$ python --version
Python 3.6.15
(OL_textattack) studio-lab-user@default:~$ pip install textattack
Collecting textattack
  Downloading textattack-0.3.7-py3-none-any.whl (418 kB)
     |████████████████████████████████| 418 kB 5.3 MB/s 
Collecting torch!=1.8,>=1.7.0
  Downloading torch-1.10.2-cp36-cp36m-manylinux1_x86_64.whl (881.9 MB)
     |████████████████████████████████| 881.9 MB 8.0 kB/s 
Collecting click<8.1.0
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting filelock
  Using cached filelock-3.4.1-py3-none-any.whl (9.9 kB)
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting OpenHowNet
  Downloading OpenHowNet-2.0-py3-none-any.whl (18 kB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting scipy>=1.4.1
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 53.9 MB/s 
Collecting more-itertools
  Downloading more_itertools-8.14.0-py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 2.5 MB/s 
Collecting datasets==2.4.0
  Downloading datasets-2.4.0-py3-none-any.whl (365 kB)
     |████████████████████████████████| 365 kB 81.0 MB/s 
Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
Collecting pandas>=1.0.1
  Using cached pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
Collecting textattack
  Downloading textattack-0.3.5-py3-none-any.whl (415 kB)
     |████████████████████████████████| 415 kB 68.2 MB/s 
Collecting lru-dict
  Downloading lru_dict-1.1.8-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Collecting bert-score>=0.3.5
  Using cached bert_score-0.3.11-py3-none-any.whl (60 kB)
Collecting flair
  Downloading flair-0.11.3-py3-none-any.whl (401 kB)
     |████████████████████████████████| 401 kB 78.6 MB/s 
Collecting editdistance
  Downloading editdistance-0.6.0-cp36-cp36m-manylinux2010_x86_64.whl (284 kB)
     |████████████████████████████████| 284 kB 55.6 MB/s 
Collecting jieba
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
     |████████████████████████████████| 19.2 MB 34.3 MB/s 
Collecting nltk
  Using cached nltk-3.6.7-py3-none-any.whl (1.5 MB)
Collecting pycld2
  Downloading pycld2-0.41.tar.gz (41.4 MB)
     |████████████████████████████████| 41.4 MB 35.7 MB/s 
Collecting num2words
  Downloading num2words-0.5.12-py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 19.7 MB/s 
Collecting pinyin==0.4.0
  Downloading pinyin-0.4.0.tar.gz (3.6 MB)
     |████████████████████████████████| 3.6 MB 30.6 MB/s 
Collecting terminaltables
  Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Collecting numpy>=1.19.2
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 16.1 MB/s 
Collecting transformers>=3.3.0
  Using cached transformers-4.18.0-py3-none-any.whl (4.0 MB)
Collecting language-tool-python
  Downloading language_tool_python-2.7.1-py3-none-any.whl (34 kB)
Collecting lemminflect
  Downloading lemminflect-0.2.2-py3-none-any.whl (769 kB)
     |████████████████████████████████| 769 kB 54.7 MB/s 
Collecting datasets==1.15
  Downloading datasets-1.15.0-py3-none-any.whl (290 kB)
     |████████████████████████████████| 290 kB 66.1 MB/s 
Collecting dill
  Downloading dill-0.3.4-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 12.3 MB/s 
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting xxhash
  Downloading xxhash-3.0.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (211 kB)
     |████████████████████████████████| 211 kB 34.8 MB/s 
Collecting dataclasses
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting pyarrow!=4.0.0,>=1.0.0
  Downloading pyarrow-6.0.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25.6 MB)
     |████████████████████████████████| 25.6 MB 39.0 MB/s 
Collecting multiprocess
  Downloading multiprocess-0.70.12.2-py36-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 69.5 MB/s 
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 37.5 MB/s 
Collecting importlib-metadata
  Using cached importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting requests>=2.19.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting fsspec[http]>=2021.05.0
  Downloading fsspec-2022.1.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 77.4 MB/s 
Collecting huggingface-hub<0.1.0,>=0.0.19
  Downloading huggingface_hub-0.0.19-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 11.4 MB/s 
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (603 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pytz>=2017.2
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     |████████████████████████████████| 160 kB 81.0 MB/s 
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting importlib-resources
  Using cached importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting transformers>=3.3.0
  Downloading transformers-4.17.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 35.1 MB/s 
  Downloading transformers-4.16.2-py3-none-any.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 33.7 MB/s 
Collecting tokenizers!=0.11.3,>=0.10.1
  Using cached tokenizers-0.12.1-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
Collecting transformers>=3.3.0
  Downloading transformers-4.16.1-py3-none-any.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 37.3 MB/s 
  Downloading transformers-4.16.0-py3-none-any.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 38.5 MB/s 
  Downloading transformers-4.15.0-py3-none-any.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 36.1 MB/s 
  Downloading transformers-4.14.1-py3-none-any.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 36.8 MB/s 
  Downloading transformers-4.13.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 23.2 MB/s 
  Downloading transformers-4.12.5-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 26.4 MB/s 
  Downloading transformers-4.12.4-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 35.7 MB/s 
  Downloading transformers-4.12.3-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 39.8 MB/s 
  Downloading transformers-4.12.2-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 41.0 MB/s 
Collecting sacremoses
  Using cached sacremoses-0.0.53-py3-none-any.whl
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 36.8 MB/s 
Collecting regex!=2019.12.17
  Using cached regex-2022.8.17-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
Collecting idna-ssl>=1.0
  Downloading idna-ssl-1.1.0.tar.gz (3.4 kB)
Collecting attrs>=17.3.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 12.9 MB/s 
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.2.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (191 kB)
     |████████████████████████████████| 191 kB 77.1 MB/s 
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (270 kB)
     |████████████████████████████████| 270 kB 54.9 MB/s 
Collecting multidict<7.0,>=4.5
  Downloading multidict-5.2.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (159 kB)
     |████████████████████████████████| 159 kB 51.7 MB/s 
Collecting deprecated>=1.2.4
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting ftfy
  Downloading ftfy-6.0.3.tar.gz (64 kB)
     |████████████████████████████████| 64 kB 6.5 MB/s 
Collecting gensim>=3.4.0
  Downloading gensim-4.2.0.tar.gz (23.2 MB)
     |████████████████████████████████| 23.2 MB 28.1 MB/s 
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     |████████████████████████████████| 981 kB 50.0 MB/s 
Collecting conllu>=4.0
  Downloading conllu-4.5.2-py2.py3-none-any.whl (16 kB)
Collecting lxml
  Downloading lxml-4.9.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 53.9 MB/s 
Collecting konoha<5.0.0,>=4.0.0
  Downloading konoha-4.6.5-py3-none-any.whl (20 kB)
Collecting segtok>=1.5.7
  Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Collecting mpld3==0.3
  Downloading mpld3-0.3.tar.gz (788 kB)
     |████████████████████████████████| 788 kB 53.7 MB/s 
Collecting tabulate
  Downloading tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting sqlitedict>=1.6.0
  Downloading sqlitedict-2.0.0.tar.gz (46 kB)
     |████████████████████████████████| 46 kB 8.2 MB/s 
Collecting bpemb>=0.3.2
  Downloading bpemb-0.3.3-py3-none-any.whl (19 kB)
Collecting scikit-learn>=0.21.3
  Downloading scikit_learn-0.24.2-cp36-cp36m-manylinux2010_x86_64.whl (22.2 MB)
     |████████████████████████████████| 22.2 MB 29.5 MB/s 
Collecting pptree
  Downloading pptree-3.1.tar.gz (3.0 kB)
Collecting hyperopt>=0.2.7
  Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 33.7 MB/s 
Collecting sentencepiece==0.1.95
  Downloading sentencepiece-0.1.95-cp36-cp36m-manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 52.0 MB/s 
Collecting gdown==4.4.0
  Downloading gdown-4.4.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting janome
  Downloading Janome-0.4.2-py2.py3-none-any.whl (19.7 MB)
     |████████████████████████████████| 19.7 MB 11.4 MB/s 
Collecting wikipedia-api
  Downloading Wikipedia-API-0.5.4.tar.gz (18 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 41.2 MB/s 
Collecting wrapt<2,>=1.10
  Using cached wrapt-1.14.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (74 kB)
Collecting smart_open>=1.8.1
  Downloading smart_open-6.1.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 12.2 MB/s 
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 46.2 MB/s 
Collecting networkx>=2.2
  Downloading networkx-2.5.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 23.8 MB/s 
Collecting py4j
  Downloading py4j-0.10.9.7-py2.py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 28.7 MB/s 
Collecting cloudpickle
  Downloading cloudpickle-2.2.0-py3-none-any.whl (25 kB)
Collecting importlib-metadata
  Downloading importlib_metadata-3.10.1-py3-none-any.whl (14 kB)
Collecting overrides<4.0.0,>=3.0.0
  Downloading overrides-3.1.0.tar.gz (11 kB)
Collecting zipp>=0.5
  Using cached zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 57.9 MB/s 
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting decorator<5,>=4.3
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting docopt>=0.6.2
  Downloading docopt-0.6.2.tar.gz (25 kB)
Requirement already satisfied: setuptools in ./.conda/envs/OL_textattack/lib/python3.6/site-packages (from OpenHowNet->textattack) (49.6.0.post20210108)
Collecting anytree
  Downloading anytree-2.8.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.5 MB/s 
Building wheels for collected packages: pinyin, idna-ssl, gdown, mpld3, gensim, overrides, sqlitedict, ftfy, future, jieba, langdetect, docopt, pptree, pycld2, wikipedia-api, word2number
  Building wheel for pinyin (setup.py) ... done
  Created wheel for pinyin: filename=pinyin-0.4.0-py3-none-any.whl size=3630484 sha256=61dfa546e82aa3465e916e3ab0cdae65c1205959e2840d3c6db80141ec09b9e9
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/3e/e6/77/88bbd152bba66174af6bfb307aebc54ed224102c87bf86ad58
  Building wheel for idna-ssl (setup.py) ... done
  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-py3-none-any.whl size=3160 sha256=ea92cc07de86a99ec961118e287719fd62c0550e2b547a217d68fdd458a0d749
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/6a/f5/9c/f8331a854f7a8739cf0e74c13854e4dd7b1af11b04fe1dde13
  Building wheel for gdown (PEP 517) ... done
  Created wheel for gdown: filename=gdown-4.4.0-py3-none-any.whl size=14774 sha256=68cb257c19a9aa8d0d92c6dda150448ef2efb6ba908b1aa4bef22397bd84430d
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/96/f9/d3/4594b3b2fe2ee239d0c9eb861f468204652e0a1c6d03755d75
  Building wheel for mpld3 (setup.py) ... done
  Created wheel for mpld3: filename=mpld3-0.3-py3-none-any.whl size=116678 sha256=411463636da62f447a126a325e8d05e11356ea155e71ec814e5546f5ded7a8d9
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/c0/74/c9/ac92f0c4c9eb137d440e86c2822aba0b96b63e608dd5737164
  Building wheel for gensim (setup.py) ... done
  Created wheel for gensim: filename=gensim-4.2.0-cp36-cp36m-linux_x86_64.whl size=26323701 sha256=ffb55cf17c1800749483380810c9bfc733dd1b2905634499b5dc7282d5a95d0f
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/44/1e/2b/b0056a533d057c3ed56c84fbdd79cca690496f4cd7c03c157c
  Building wheel for overrides (setup.py) ... done
  Created wheel for overrides: filename=overrides-3.1.0-py3-none-any.whl size=10174 sha256=25bb4645001598765d85d3b8df4f0e3facbc02fcce1351572ce5c78ae416d594
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/e6/3b/34/ae59fc8d35c37f01099425ab73599e45e9b9b599a7ccc2c45f
  Building wheel for sqlitedict (setup.py) ... done
  Created wheel for sqlitedict: filename=sqlitedict-2.0.0-py3-none-any.whl size=15718 sha256=51260edcc09fc19e87c86fa70834bf5841a93f7d5a72816f40f3d0ddfb930f60
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/c3/ea/90/1812907e81ceb6c0393eb6802f7aba97d4ee157b0e15bc8101
  Building wheel for ftfy (setup.py) ... done
  Created wheel for ftfy: filename=ftfy-6.0.3-py3-none-any.whl size=41914 sha256=45a41caec9063598f8415246e0e8e9df6233cda464e131402dbfce9c76f7404b
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/ff/2a/24/75041425faf3347ab146a4a3d0484f723b2c44a7966a06e3f0
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=dbaf5aea82f09b0d0937ea092747109aecacb4080670399b2dd1a96438dcb399
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
  Building wheel for jieba (setup.py) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314478 sha256=14f7388b5355d0fce1e7bed48395e939d04578e7562c1ad166255bd4b2a73f8b
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/17/a7/8b/a7e03881534e78558920ac68aaeca05180c0e2c3d11c4fce3b
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=37de88a04344124321fc35ef83ae8dbe22f01517e9a79134c83edfcf02027a3d
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/22/e8/62/ef79403841bab16f1c4260b967bee7fa579d78552a66c7f6e0
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=6d192bfbbc9fb7eeac8629ccb02398eb99b2c8310a5699a5748484bd7900a866
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/3f/2a/fa/4d7a888e69774d5e6e855d190a8a51b357d77cc05eb1c097c9
  Building wheel for pptree (setup.py) ... done
  Created wheel for pptree: filename=pptree-3.1-py3-none-any.whl size=4629 sha256=b96c734a1fac428fbd0be5234a6f2c533e63750bcd9f9cd0781a7406a5f965d2
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/49/96/59/c79bd5a81766eff592a2c8964a13eaa5399ee1aed1d98f87a5
  Building wheel for pycld2 (setup.py) ... done
  Created wheel for pycld2: filename=pycld2-0.41-cp36-cp36m-linux_x86_64.whl size=9917726 sha256=507b0090a68756079c86d3f576ceac0c0fcd8c6d2ebcccad27d14d33bca791df
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/6b/7e/07/b9336468d80bec16f1d07cb4d6fd0509478618d360e4175f8d
  Building wheel for wikipedia-api (setup.py) ... done
  Created wheel for wikipedia-api: filename=Wikipedia_API-0.5.4-py3-none-any.whl size=13462 sha256=c68d736b32d3921c155234aa126438f125b90a21b68b50cf46dd9d0ec6ad7d24
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/df/ef/26/efdbba65d2518a939c023f11f7d60a7f5d3405d47e51bbafdd
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5586 sha256=90ab83e5146a1a6c4f989fd7c15721caad8d9a75c520e0639f467c1aec58d0c6
  Stored in directory: /home/studio-lab-user/.cache/pip/wheels/6c/5e/36/8b922f014b64e2a45bac622008bc439281784eb1e09fe5d8d5
Successfully built pinyin idna-ssl gdown mpld3 gensim overrides sqlitedict ftfy future jieba langdetect docopt pptree pycld2 wikipedia-api word2number
Installing collected packages: zipp, typing-extensions, urllib3, pyparsing, numpy, multidict, importlib-resources, importlib-metadata, idna, frozenlist, charset-normalizer, certifi, yarl, tqdm, soupsieve, smart-open, six, scipy, requests, regex, pyyaml, PySocks, packaging, joblib, idna-ssl, filelock, decorator, click, attrs, asynctest, async-timeout, aiosignal, wrapt, wcwidth, tokenizers, threadpoolctl, sentencepiece, sacremoses, pytz, python-dateutil, py4j, pillow, overrides, networkx, kiwisolver, huggingface-hub, gensim, future, fsspec, dill, dataclasses, cycler, cloudpickle, beautifulsoup4, aiohttp, xxhash, wikipedia-api, transformers, torch, tabulate, sqlitedict, segtok, scikit-learn, pyarrow, pptree, pandas, multiprocess, mpld3, more-itertools, matplotlib, lxml, langdetect, konoha, janome, hyperopt, gdown, ftfy, docopt, deprecated, conllu, bpemb, anytree, word2number, terminaltables, pycld2, pinyin, OpenHowNet, num2words, nltk, lru-dict, lemminflect, language-tool-python, jieba, flair, editdistance, datasets, bert-score, textattack
  Attempting uninstall: certifi
    Found existing installation: certifi 2016.9.26
ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
(OL_textattack) studio-lab-user@default:~$ textattack --help
bash: textattack: command not found
```

**Comment by otterlover24** [comment]
The following command resolved the previous issue:

`OL_textattack) studio-lab-user@default:~$ pip install textattack --ignore-installed certifi`

However, a new error of missing module 'tensorflow_text' appeared.

```
(OL_textattack) studio-lab-user@default:~$ textattack --help
textattack: Updating TextAttack package dependencies.
textattack: Downloading NLTK required packages.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/studio-lab-user/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package omw to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data] Downloading package universal_tagset to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!
[nltk_data] Downloading package wordnet to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/OL_textattack/bin/textattack", line 5, in <module>
    from textattack.commands.textattack_cli import main
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/__init__.py", line 11, in <module>
    from .attack_args import AttackArgs, CommandLineAttackArgs
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/attack_args.py", line 15, in <module>
    from .attack import Attack
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/attack.py", line 19, in <module>
    from textattack.constraints import Constraint, PreTransformationConstraint
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/constraints/__init__.py", line 25, in <module>
    from . import semantics
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/constraints/semantics/__init__.py", line 7, in <module>
    from . import sentence_encoders
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/constraints/semantics/sentence_encoders/__init__.py", line 12, in <module>
    from .universal_sentence_encoder import (
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/__init__.py", line 8, in <module>
    from .multilingual_universal_sentence_encoder import (
  File "/home/studio-lab-user/.conda/envs/OL_textattack/lib/python3.6/site-packages/textattack/constraints/semantics/sentence_encoders/universal_sentence_encoder/multilingual_universal_sentence_encoder.py", line 5, in <module>
    import tensorflow_text  # noqa: F401
ModuleNotFoundError: No module named 'tensorflow_text'
```

**Comment by otterlover24** [comment]
The following command solved the previous installation / dependency issue:

```
(OL_textattack) studio-lab-user@default:~$ pip install textattack tensorflow_text --ignore-installed certifi
```
