### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Y-0919** [QData/TextAttack#760]
$ pip install textattack
Defaulting to user installation because normal site-packages is not writeable
Collecting textattack
  Using cached textattack-0.3.9-py3-none-any.whl.metadata (37 kB)
Collecting bert-score>=0.3.5 (from textattack)
  Using cached bert_score-0.3.13-py3-none-any.whl (61 kB)
Collecting editdistance (from textattack)
  Using cached editdistance-0.6.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/yomo0791/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py                                 ", line 353, in <module>
          main()
        File "/home/yomo0791/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py                                 ", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/yomo0791/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py                                 ", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in                                  get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in                                  _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in                                  run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1010                                 , in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 845,                                  in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-ptept65m/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 117,                                  in nonempty
          raise ValueError(error_msg)
      ValueError: 'editdistance/bycython.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I got the above error when I used "pip install textattack". Anyone know how to solve this?

**Comment by Minimindy** [comment]
#720

**Comment by qiyanjun** [comment]
This is a \`editdistance\` wheel-build failure specifically (a C-extension package, still a real TextAttack dependency) — related in *kind* to #720's \`pycld2\` build failure (both are "no C++ build toolchain available for a native-extension pip dependency"), but not the same package, so not a true duplicate. This isn't something to fix in TextAttack's code — it's standard Python packaging friction on systems missing build tools. Closing as an environment/toolchain issue rather than a library bug; if you're still blocked, installing build tools for your platform (e.g. Visual C++ Build Tools on Windows, \`build-essential\` on Debian/Ubuntu) should resolve the underlying \`editdistance\` build failure.
